// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.echo.protocol



sealed trait AuthType extends com.trueaccord.scalapb.GeneratedEnum {
  type EnumType = AuthType
  def isAuthTypeEmpty: Boolean = false
  def isLocal: Boolean = false
  def isWechat: Boolean = false
  def isWeibo: Boolean = false
  def isUnrecognized: Boolean = false
  def companion: com.trueaccord.scalapb.GeneratedEnumCompanion[AuthType] = AuthType
}

object AuthType extends com.trueaccord.scalapb.GeneratedEnumCompanion[AuthType] {
  implicit def enumCompanion: com.trueaccord.scalapb.GeneratedEnumCompanion[AuthType] = this
  @SerialVersionUID(0L)
  case object AUTH_TYPE_EMPTY extends AuthType {
    val value = 0
    val index = 0
    val name = "AUTH_TYPE_EMPTY"
    override def isAuthTypeEmpty: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object LOCAL extends AuthType {
    val value = 1
    val index = 1
    val name = "LOCAL"
    override def isLocal: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object WECHAT extends AuthType {
    val value = 2
    val index = 2
    val name = "WECHAT"
    override def isWechat: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object WEIBO extends AuthType {
    val value = 3
    val index = 3
    val name = "WEIBO"
    override def isWeibo: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case class Unrecognized(value: Int) extends AuthType {
    val name = "UNRECOGNIZED"
    val index = -1
    override def isUnrecognized: Boolean = true
  }
  
  lazy val values = Seq(AUTH_TYPE_EMPTY, LOCAL, WECHAT, WEIBO)
  def fromValue(value: Int): AuthType = value match {
    case 0 => AUTH_TYPE_EMPTY
    case 1 => LOCAL
    case 2 => WECHAT
    case 3 => WEIBO
    case __other => Unrecognized(__other)
  }
  def descriptor: com.google.protobuf.Descriptors.EnumDescriptor = ProtocolComEchoProtocolProto.descriptor.getEnumTypes.get(2)
}