// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.echo.protocol



sealed trait LoginType extends com.trueaccord.scalapb.GeneratedEnum {
  type EnumType = LoginType
  def isLoginTypeEmpty: Boolean = false
  def isLoginByUsername: Boolean = false
  def isLoginByPhonenum: Boolean = false
  def isLoginByEmail: Boolean = false
  def isUnrecognized: Boolean = false
  def companion: com.trueaccord.scalapb.GeneratedEnumCompanion[LoginType] = LoginType
}

object LoginType extends com.trueaccord.scalapb.GeneratedEnumCompanion[LoginType] {
  implicit def enumCompanion: com.trueaccord.scalapb.GeneratedEnumCompanion[LoginType] = this
  @SerialVersionUID(0L)
  case object LOGIN_TYPE_EMPTY extends LoginType {
    val value = 0
    val index = 0
    val name = "LOGIN_TYPE_EMPTY"
    override def isLoginTypeEmpty: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object LOGIN_BY_USERNAME extends LoginType {
    val value = 1
    val index = 1
    val name = "LOGIN_BY_USERNAME"
    override def isLoginByUsername: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object LOGIN_BY_PHONENUM extends LoginType {
    val value = 2
    val index = 2
    val name = "LOGIN_BY_PHONENUM"
    override def isLoginByPhonenum: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object LOGIN_BY_EMAIL extends LoginType {
    val value = 3
    val index = 3
    val name = "LOGIN_BY_EMAIL"
    override def isLoginByEmail: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case class Unrecognized(value: Int) extends LoginType {
    val name = "UNRECOGNIZED"
    val index = -1
    override def isUnrecognized: Boolean = true
  }
  
  lazy val values = Seq(LOGIN_TYPE_EMPTY, LOGIN_BY_USERNAME, LOGIN_BY_PHONENUM, LOGIN_BY_EMAIL)
  def fromValue(value: Int): LoginType = value match {
    case 0 => LOGIN_TYPE_EMPTY
    case 1 => LOGIN_BY_USERNAME
    case 2 => LOGIN_BY_PHONENUM
    case 3 => LOGIN_BY_EMAIL
    case __other => Unrecognized(__other)
  }
  def descriptor: com.google.protobuf.Descriptors.EnumDescriptor = ProtocolComEchoProtocolProto.descriptor.getEnumTypes.get(1)
}