// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.echo.protocol



@SerialVersionUID(0L)
final case class Response(
    result: com.echo.protocol.ResultCode = com.echo.protocol.ResultCode.SUCCESS,
    errorDescription: String = "",
    content: com.echo.protocol.Response.Content = com.echo.protocol.Response.Content.Empty
    ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[Response] with com.trueaccord.lenses.Updatable[Response] {
    @transient
    lazy val serializedSize: Int = {
      var __size = 0
      if (result != com.echo.protocol.ResultCode.SUCCESS) { __size += com.google.protobuf.CodedOutputStream.computeEnumSize(1, result.value) }
      if (errorDescription != "") { __size += com.google.protobuf.CodedOutputStream.computeStringSize(2, errorDescription) }
      if (content.signupResponse.isDefined) { __size += 2 + com.google.protobuf.CodedOutputStream.computeRawVarint32Size(content.signupResponse.get.serializedSize) + content.signupResponse.get.serializedSize }
      if (content.loginResponse.isDefined) { __size += 2 + com.google.protobuf.CodedOutputStream.computeRawVarint32Size(content.loginResponse.get.serializedSize) + content.loginResponse.get.serializedSize }
      if (content.authenticationResponse.isDefined) { __size += 2 + com.google.protobuf.CodedOutputStream.computeRawVarint32Size(content.authenticationResponse.get.serializedSize) + content.authenticationResponse.get.serializedSize }
      if (content.logoutResponse.isDefined) { __size += 2 + com.google.protobuf.CodedOutputStream.computeRawVarint32Size(content.logoutResponse.get.serializedSize) + content.logoutResponse.get.serializedSize }
      if (content.queryUserInfoResponse.isDefined) { __size += 2 + com.google.protobuf.CodedOutputStream.computeRawVarint32Size(content.queryUserInfoResponse.get.serializedSize) + content.queryUserInfoResponse.get.serializedSize }
      if (content.updateUsernameResponse.isDefined) { __size += 2 + com.google.protobuf.CodedOutputStream.computeRawVarint32Size(content.updateUsernameResponse.get.serializedSize) + content.updateUsernameResponse.get.serializedSize }
      if (content.updatePhonenumResponse.isDefined) { __size += 2 + com.google.protobuf.CodedOutputStream.computeRawVarint32Size(content.updatePhonenumResponse.get.serializedSize) + content.updatePhonenumResponse.get.serializedSize }
      if (content.updateEmailResponse.isDefined) { __size += 2 + com.google.protobuf.CodedOutputStream.computeRawVarint32Size(content.updateEmailResponse.get.serializedSize) + content.updateEmailResponse.get.serializedSize }
      if (content.updatePasswordResponse.isDefined) { __size += 2 + com.google.protobuf.CodedOutputStream.computeRawVarint32Size(content.updatePasswordResponse.get.serializedSize) + content.updatePasswordResponse.get.serializedSize }
      if (content.updateSecQuestionResponse.isDefined) { __size += 2 + com.google.protobuf.CodedOutputStream.computeRawVarint32Size(content.updateSecQuestionResponse.get.serializedSize) + content.updateSecQuestionResponse.get.serializedSize }
      if (content.addUserAddressReponse.isDefined) { __size += 2 + com.google.protobuf.CodedOutputStream.computeRawVarint32Size(content.addUserAddressReponse.get.serializedSize) + content.addUserAddressReponse.get.serializedSize }
      if (content.updateUserAddressReponse.isDefined) { __size += 2 + com.google.protobuf.CodedOutputStream.computeRawVarint32Size(content.updateUserAddressReponse.get.serializedSize) + content.updateUserAddressReponse.get.serializedSize }
      if (content.deleteUserAddressReponse.isDefined) { __size += 2 + com.google.protobuf.CodedOutputStream.computeRawVarint32Size(content.deleteUserAddressReponse.get.serializedSize) + content.deleteUserAddressReponse.get.serializedSize }
      __size
    }
    def writeTo(output: com.google.protobuf.CodedOutputStream): Unit = {
      {
        val __v = result
        if (__v != com.echo.protocol.ResultCode.SUCCESS) {
          output.writeEnum(1, __v.value)
        }
      };
      {
        val __v = errorDescription
        if (__v != "") {
          output.writeString(2, __v)
        }
      };
      content.signupResponse.foreach { __v => 
        output.writeTag(1001, 2)
        output.writeRawVarint32(__v.serializedSize)
        __v.writeTo(output)
      };
      content.loginResponse.foreach { __v => 
        output.writeTag(1002, 2)
        output.writeRawVarint32(__v.serializedSize)
        __v.writeTo(output)
      };
      content.authenticationResponse.foreach { __v => 
        output.writeTag(1003, 2)
        output.writeRawVarint32(__v.serializedSize)
        __v.writeTo(output)
      };
      content.logoutResponse.foreach { __v => 
        output.writeTag(1004, 2)
        output.writeRawVarint32(__v.serializedSize)
        __v.writeTo(output)
      };
      content.queryUserInfoResponse.foreach { __v => 
        output.writeTag(1005, 2)
        output.writeRawVarint32(__v.serializedSize)
        __v.writeTo(output)
      };
      content.updateUsernameResponse.foreach { __v => 
        output.writeTag(1006, 2)
        output.writeRawVarint32(__v.serializedSize)
        __v.writeTo(output)
      };
      content.updatePhonenumResponse.foreach { __v => 
        output.writeTag(1007, 2)
        output.writeRawVarint32(__v.serializedSize)
        __v.writeTo(output)
      };
      content.updateEmailResponse.foreach { __v => 
        output.writeTag(1008, 2)
        output.writeRawVarint32(__v.serializedSize)
        __v.writeTo(output)
      };
      content.updatePasswordResponse.foreach { __v => 
        output.writeTag(1009, 2)
        output.writeRawVarint32(__v.serializedSize)
        __v.writeTo(output)
      };
      content.updateSecQuestionResponse.foreach { __v => 
        output.writeTag(1010, 2)
        output.writeRawVarint32(__v.serializedSize)
        __v.writeTo(output)
      };
      content.addUserAddressReponse.foreach { __v => 
        output.writeTag(1100, 2)
        output.writeRawVarint32(__v.serializedSize)
        __v.writeTo(output)
      };
      content.updateUserAddressReponse.foreach { __v => 
        output.writeTag(1101, 2)
        output.writeRawVarint32(__v.serializedSize)
        __v.writeTo(output)
      };
      content.deleteUserAddressReponse.foreach { __v => 
        output.writeTag(1102, 2)
        output.writeRawVarint32(__v.serializedSize)
        __v.writeTo(output)
      };
    }
    def mergeFrom(__input: com.google.protobuf.CodedInputStream): com.echo.protocol.Response = {
      var __result = this.result
      var __errorDescription = this.errorDescription
      var __content = this.content
      var _done__ = false
      while (!_done__) {
        val _tag__ = __input.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 8 =>
            __result = com.echo.protocol.ResultCode.fromValue(__input.readEnum())
          case 18 =>
            __errorDescription = __input.readString()
          case 8010 =>
            __content = com.echo.protocol.Response.Content.SignupResponse(com.trueaccord.scalapb.LiteParser.readMessage(__input, content.signupResponse.getOrElse(com.echo.protocol.Response.SignupResponse.defaultInstance)))
          case 8018 =>
            __content = com.echo.protocol.Response.Content.LoginResponse(com.trueaccord.scalapb.LiteParser.readMessage(__input, content.loginResponse.getOrElse(com.echo.protocol.Response.LoginResponse.defaultInstance)))
          case 8026 =>
            __content = com.echo.protocol.Response.Content.AuthenticationResponse(com.trueaccord.scalapb.LiteParser.readMessage(__input, content.authenticationResponse.getOrElse(com.echo.protocol.Response.AuthenticationResponse.defaultInstance)))
          case 8034 =>
            __content = com.echo.protocol.Response.Content.LogoutResponse(com.trueaccord.scalapb.LiteParser.readMessage(__input, content.logoutResponse.getOrElse(com.echo.protocol.Response.LogoutResponse.defaultInstance)))
          case 8042 =>
            __content = com.echo.protocol.Response.Content.QueryUserInfoResponse(com.trueaccord.scalapb.LiteParser.readMessage(__input, content.queryUserInfoResponse.getOrElse(com.echo.protocol.Response.QueryUserInfoResponse.defaultInstance)))
          case 8050 =>
            __content = com.echo.protocol.Response.Content.UpdateUsernameResponse(com.trueaccord.scalapb.LiteParser.readMessage(__input, content.updateUsernameResponse.getOrElse(com.echo.protocol.Response.UpdateUsernameResponse.defaultInstance)))
          case 8058 =>
            __content = com.echo.protocol.Response.Content.UpdatePhonenumResponse(com.trueaccord.scalapb.LiteParser.readMessage(__input, content.updatePhonenumResponse.getOrElse(com.echo.protocol.Response.UpdatePhonenumResponse.defaultInstance)))
          case 8066 =>
            __content = com.echo.protocol.Response.Content.UpdateEmailResponse(com.trueaccord.scalapb.LiteParser.readMessage(__input, content.updateEmailResponse.getOrElse(com.echo.protocol.Response.UpdateEmailResponse.defaultInstance)))
          case 8074 =>
            __content = com.echo.protocol.Response.Content.UpdatePasswordResponse(com.trueaccord.scalapb.LiteParser.readMessage(__input, content.updatePasswordResponse.getOrElse(com.echo.protocol.Response.UpdatePasswordResponse.defaultInstance)))
          case 8082 =>
            __content = com.echo.protocol.Response.Content.UpdateSecQuestionResponse(com.trueaccord.scalapb.LiteParser.readMessage(__input, content.updateSecQuestionResponse.getOrElse(com.echo.protocol.Response.UpdateSecQuestionResponse.defaultInstance)))
          case 8802 =>
            __content = com.echo.protocol.Response.Content.AddUserAddressReponse(com.trueaccord.scalapb.LiteParser.readMessage(__input, content.addUserAddressReponse.getOrElse(com.echo.protocol.Response.AddUserAddressResponse.defaultInstance)))
          case 8810 =>
            __content = com.echo.protocol.Response.Content.UpdateUserAddressReponse(com.trueaccord.scalapb.LiteParser.readMessage(__input, content.updateUserAddressReponse.getOrElse(com.echo.protocol.Response.UpdateUserAddressResponse.defaultInstance)))
          case 8818 =>
            __content = com.echo.protocol.Response.Content.DeleteUserAddressReponse(com.trueaccord.scalapb.LiteParser.readMessage(__input, content.deleteUserAddressReponse.getOrElse(com.echo.protocol.Response.DeleteUserAddressResponse.defaultInstance)))
          case tag => __input.skipField(tag)
        }
      }
      com.echo.protocol.Response(
          result = __result,
          errorDescription = __errorDescription,
          content = __content
      )
    }
    def withResult(__v: com.echo.protocol.ResultCode): Response = copy(result = __v)
    def withErrorDescription(__v: String): Response = copy(errorDescription = __v)
    def getSignupResponse: com.echo.protocol.Response.SignupResponse = content.signupResponse.getOrElse(com.echo.protocol.Response.SignupResponse.defaultInstance)
    def withSignupResponse(__v: com.echo.protocol.Response.SignupResponse): Response = copy(content = com.echo.protocol.Response.Content.SignupResponse(__v))
    def getLoginResponse: com.echo.protocol.Response.LoginResponse = content.loginResponse.getOrElse(com.echo.protocol.Response.LoginResponse.defaultInstance)
    def withLoginResponse(__v: com.echo.protocol.Response.LoginResponse): Response = copy(content = com.echo.protocol.Response.Content.LoginResponse(__v))
    def getAuthenticationResponse: com.echo.protocol.Response.AuthenticationResponse = content.authenticationResponse.getOrElse(com.echo.protocol.Response.AuthenticationResponse.defaultInstance)
    def withAuthenticationResponse(__v: com.echo.protocol.Response.AuthenticationResponse): Response = copy(content = com.echo.protocol.Response.Content.AuthenticationResponse(__v))
    def getLogoutResponse: com.echo.protocol.Response.LogoutResponse = content.logoutResponse.getOrElse(com.echo.protocol.Response.LogoutResponse.defaultInstance)
    def withLogoutResponse(__v: com.echo.protocol.Response.LogoutResponse): Response = copy(content = com.echo.protocol.Response.Content.LogoutResponse(__v))
    def getQueryUserInfoResponse: com.echo.protocol.Response.QueryUserInfoResponse = content.queryUserInfoResponse.getOrElse(com.echo.protocol.Response.QueryUserInfoResponse.defaultInstance)
    def withQueryUserInfoResponse(__v: com.echo.protocol.Response.QueryUserInfoResponse): Response = copy(content = com.echo.protocol.Response.Content.QueryUserInfoResponse(__v))
    def getUpdateUsernameResponse: com.echo.protocol.Response.UpdateUsernameResponse = content.updateUsernameResponse.getOrElse(com.echo.protocol.Response.UpdateUsernameResponse.defaultInstance)
    def withUpdateUsernameResponse(__v: com.echo.protocol.Response.UpdateUsernameResponse): Response = copy(content = com.echo.protocol.Response.Content.UpdateUsernameResponse(__v))
    def getUpdatePhonenumResponse: com.echo.protocol.Response.UpdatePhonenumResponse = content.updatePhonenumResponse.getOrElse(com.echo.protocol.Response.UpdatePhonenumResponse.defaultInstance)
    def withUpdatePhonenumResponse(__v: com.echo.protocol.Response.UpdatePhonenumResponse): Response = copy(content = com.echo.protocol.Response.Content.UpdatePhonenumResponse(__v))
    def getUpdateEmailResponse: com.echo.protocol.Response.UpdateEmailResponse = content.updateEmailResponse.getOrElse(com.echo.protocol.Response.UpdateEmailResponse.defaultInstance)
    def withUpdateEmailResponse(__v: com.echo.protocol.Response.UpdateEmailResponse): Response = copy(content = com.echo.protocol.Response.Content.UpdateEmailResponse(__v))
    def getUpdatePasswordResponse: com.echo.protocol.Response.UpdatePasswordResponse = content.updatePasswordResponse.getOrElse(com.echo.protocol.Response.UpdatePasswordResponse.defaultInstance)
    def withUpdatePasswordResponse(__v: com.echo.protocol.Response.UpdatePasswordResponse): Response = copy(content = com.echo.protocol.Response.Content.UpdatePasswordResponse(__v))
    def getUpdateSecQuestionResponse: com.echo.protocol.Response.UpdateSecQuestionResponse = content.updateSecQuestionResponse.getOrElse(com.echo.protocol.Response.UpdateSecQuestionResponse.defaultInstance)
    def withUpdateSecQuestionResponse(__v: com.echo.protocol.Response.UpdateSecQuestionResponse): Response = copy(content = com.echo.protocol.Response.Content.UpdateSecQuestionResponse(__v))
    def getAddUserAddressReponse: com.echo.protocol.Response.AddUserAddressResponse = content.addUserAddressReponse.getOrElse(com.echo.protocol.Response.AddUserAddressResponse.defaultInstance)
    def withAddUserAddressReponse(__v: com.echo.protocol.Response.AddUserAddressResponse): Response = copy(content = com.echo.protocol.Response.Content.AddUserAddressReponse(__v))
    def getUpdateUserAddressReponse: com.echo.protocol.Response.UpdateUserAddressResponse = content.updateUserAddressReponse.getOrElse(com.echo.protocol.Response.UpdateUserAddressResponse.defaultInstance)
    def withUpdateUserAddressReponse(__v: com.echo.protocol.Response.UpdateUserAddressResponse): Response = copy(content = com.echo.protocol.Response.Content.UpdateUserAddressReponse(__v))
    def getDeleteUserAddressReponse: com.echo.protocol.Response.DeleteUserAddressResponse = content.deleteUserAddressReponse.getOrElse(com.echo.protocol.Response.DeleteUserAddressResponse.defaultInstance)
    def withDeleteUserAddressReponse(__v: com.echo.protocol.Response.DeleteUserAddressResponse): Response = copy(content = com.echo.protocol.Response.Content.DeleteUserAddressReponse(__v))
    def clearContent: Response = copy(content = com.echo.protocol.Response.Content.Empty)
    def withContent(__v: com.echo.protocol.Response.Content): Response = copy(content = __v)
    def getField(__field: com.google.protobuf.Descriptors.FieldDescriptor): scala.Any = {
      __field.getNumber match {
        case 1 => {
          val __t = result.valueDescriptor
          if (__t.getNumber() != 0) __t else null
        }
        case 2 => {
          val __t = errorDescription
          if (__t != "") __t else null
        }
        case 1001 => content.signupResponse.getOrElse(null)
        case 1002 => content.loginResponse.getOrElse(null)
        case 1003 => content.authenticationResponse.getOrElse(null)
        case 1004 => content.logoutResponse.getOrElse(null)
        case 1005 => content.queryUserInfoResponse.getOrElse(null)
        case 1006 => content.updateUsernameResponse.getOrElse(null)
        case 1007 => content.updatePhonenumResponse.getOrElse(null)
        case 1008 => content.updateEmailResponse.getOrElse(null)
        case 1009 => content.updatePasswordResponse.getOrElse(null)
        case 1010 => content.updateSecQuestionResponse.getOrElse(null)
        case 1100 => content.addUserAddressReponse.getOrElse(null)
        case 1101 => content.updateUserAddressReponse.getOrElse(null)
        case 1102 => content.deleteUserAddressReponse.getOrElse(null)
      }
    }
    override def toString: String = com.trueaccord.scalapb.TextFormat.printToUnicodeString(this)
    def companion = com.echo.protocol.Response
}

object Response extends com.trueaccord.scalapb.GeneratedMessageCompanion[Response] {
  implicit def messageCompanion: com.trueaccord.scalapb.GeneratedMessageCompanion[Response] = this
  def fromFieldsMap(__fieldsMap: Map[com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): com.echo.protocol.Response = {
    require(__fieldsMap.keys.forall(_.getContainingType() == descriptor), "FieldDescriptor does not match message type.")
    val __fields = descriptor.getFields
    com.echo.protocol.Response(
      com.echo.protocol.ResultCode.fromValue(__fieldsMap.getOrElse(__fields.get(0), com.echo.protocol.ResultCode.SUCCESS.valueDescriptor).asInstanceOf[com.google.protobuf.Descriptors.EnumValueDescriptor].getNumber),
      __fieldsMap.getOrElse(__fields.get(1), "").asInstanceOf[String],
      content = __fieldsMap.get(__fields.get(2)).asInstanceOf[scala.Option[com.echo.protocol.Response.SignupResponse]].map(com.echo.protocol.Response.Content.SignupResponse(_)) orElse
__fieldsMap.get(__fields.get(3)).asInstanceOf[scala.Option[com.echo.protocol.Response.LoginResponse]].map(com.echo.protocol.Response.Content.LoginResponse(_)) orElse
__fieldsMap.get(__fields.get(4)).asInstanceOf[scala.Option[com.echo.protocol.Response.AuthenticationResponse]].map(com.echo.protocol.Response.Content.AuthenticationResponse(_)) orElse
__fieldsMap.get(__fields.get(5)).asInstanceOf[scala.Option[com.echo.protocol.Response.LogoutResponse]].map(com.echo.protocol.Response.Content.LogoutResponse(_)) orElse
__fieldsMap.get(__fields.get(6)).asInstanceOf[scala.Option[com.echo.protocol.Response.QueryUserInfoResponse]].map(com.echo.protocol.Response.Content.QueryUserInfoResponse(_)) orElse
__fieldsMap.get(__fields.get(7)).asInstanceOf[scala.Option[com.echo.protocol.Response.UpdateUsernameResponse]].map(com.echo.protocol.Response.Content.UpdateUsernameResponse(_)) orElse
__fieldsMap.get(__fields.get(8)).asInstanceOf[scala.Option[com.echo.protocol.Response.UpdatePhonenumResponse]].map(com.echo.protocol.Response.Content.UpdatePhonenumResponse(_)) orElse
__fieldsMap.get(__fields.get(9)).asInstanceOf[scala.Option[com.echo.protocol.Response.UpdateEmailResponse]].map(com.echo.protocol.Response.Content.UpdateEmailResponse(_)) orElse
__fieldsMap.get(__fields.get(10)).asInstanceOf[scala.Option[com.echo.protocol.Response.UpdatePasswordResponse]].map(com.echo.protocol.Response.Content.UpdatePasswordResponse(_)) orElse
__fieldsMap.get(__fields.get(11)).asInstanceOf[scala.Option[com.echo.protocol.Response.UpdateSecQuestionResponse]].map(com.echo.protocol.Response.Content.UpdateSecQuestionResponse(_)) orElse
__fieldsMap.get(__fields.get(12)).asInstanceOf[scala.Option[com.echo.protocol.Response.AddUserAddressResponse]].map(com.echo.protocol.Response.Content.AddUserAddressReponse(_)) orElse
__fieldsMap.get(__fields.get(13)).asInstanceOf[scala.Option[com.echo.protocol.Response.UpdateUserAddressResponse]].map(com.echo.protocol.Response.Content.UpdateUserAddressReponse(_)) orElse
__fieldsMap.get(__fields.get(14)).asInstanceOf[scala.Option[com.echo.protocol.Response.DeleteUserAddressResponse]].map(com.echo.protocol.Response.Content.DeleteUserAddressReponse(_)) getOrElse com.echo.protocol.Response.Content.Empty
    )
  }
  def descriptor: com.google.protobuf.Descriptors.Descriptor = ProtocolProtocolProto.descriptor.getMessageTypes.get(3)
  def messageCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedMessageCompanion[_] = {
    require(__field.getContainingType() == descriptor, "FieldDescriptor does not match message type.")
    var __out: com.trueaccord.scalapb.GeneratedMessageCompanion[_] = null
    __field.getNumber match {
      case 1001 => __out = com.echo.protocol.Response.SignupResponse
      case 1002 => __out = com.echo.protocol.Response.LoginResponse
      case 1003 => __out = com.echo.protocol.Response.AuthenticationResponse
      case 1004 => __out = com.echo.protocol.Response.LogoutResponse
      case 1005 => __out = com.echo.protocol.Response.QueryUserInfoResponse
      case 1006 => __out = com.echo.protocol.Response.UpdateUsernameResponse
      case 1007 => __out = com.echo.protocol.Response.UpdatePhonenumResponse
      case 1008 => __out = com.echo.protocol.Response.UpdateEmailResponse
      case 1009 => __out = com.echo.protocol.Response.UpdatePasswordResponse
      case 1010 => __out = com.echo.protocol.Response.UpdateSecQuestionResponse
      case 1100 => __out = com.echo.protocol.Response.AddUserAddressResponse
      case 1101 => __out = com.echo.protocol.Response.UpdateUserAddressResponse
      case 1102 => __out = com.echo.protocol.Response.DeleteUserAddressResponse
    }
  __out
  }
  def enumCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedEnumCompanion[_] = {
    require(__field.getContainingType() == descriptor, "FieldDescriptor does not match message type.")
    __field.getNumber match {
      case 1 => com.echo.protocol.ResultCode
    }
  }
  lazy val defaultInstance = com.echo.protocol.Response(
  )
  sealed trait Content extends com.trueaccord.scalapb.GeneratedOneof {
    def isEmpty: Boolean = false
    def isDefined: Boolean = true
    def number: Int
    def isSignupResponse: Boolean = false
    def isLoginResponse: Boolean = false
    def isAuthenticationResponse: Boolean = false
    def isLogoutResponse: Boolean = false
    def isQueryUserInfoResponse: Boolean = false
    def isUpdateUsernameResponse: Boolean = false
    def isUpdatePhonenumResponse: Boolean = false
    def isUpdateEmailResponse: Boolean = false
    def isUpdatePasswordResponse: Boolean = false
    def isUpdateSecQuestionResponse: Boolean = false
    def isAddUserAddressReponse: Boolean = false
    def isUpdateUserAddressReponse: Boolean = false
    def isDeleteUserAddressReponse: Boolean = false
    def signupResponse: scala.Option[com.echo.protocol.Response.SignupResponse] = None
    def loginResponse: scala.Option[com.echo.protocol.Response.LoginResponse] = None
    def authenticationResponse: scala.Option[com.echo.protocol.Response.AuthenticationResponse] = None
    def logoutResponse: scala.Option[com.echo.protocol.Response.LogoutResponse] = None
    def queryUserInfoResponse: scala.Option[com.echo.protocol.Response.QueryUserInfoResponse] = None
    def updateUsernameResponse: scala.Option[com.echo.protocol.Response.UpdateUsernameResponse] = None
    def updatePhonenumResponse: scala.Option[com.echo.protocol.Response.UpdatePhonenumResponse] = None
    def updateEmailResponse: scala.Option[com.echo.protocol.Response.UpdateEmailResponse] = None
    def updatePasswordResponse: scala.Option[com.echo.protocol.Response.UpdatePasswordResponse] = None
    def updateSecQuestionResponse: scala.Option[com.echo.protocol.Response.UpdateSecQuestionResponse] = None
    def addUserAddressReponse: scala.Option[com.echo.protocol.Response.AddUserAddressResponse] = None
    def updateUserAddressReponse: scala.Option[com.echo.protocol.Response.UpdateUserAddressResponse] = None
    def deleteUserAddressReponse: scala.Option[com.echo.protocol.Response.DeleteUserAddressResponse] = None
  }
  object Content extends {
    @SerialVersionUID(0L)
    case object Empty extends Content {
      override def isEmpty: Boolean = true
      override def isDefined: Boolean = false
      override def number: Int = 0
    }
  
    @SerialVersionUID(0L)
    case class SignupResponse(value: com.echo.protocol.Response.SignupResponse) extends Content {
      override def isSignupResponse: Boolean = true
      override def signupResponse: scala.Option[com.echo.protocol.Response.SignupResponse] = Some(value)
      override def number: Int = 1001
    }
    @SerialVersionUID(0L)
    case class LoginResponse(value: com.echo.protocol.Response.LoginResponse) extends Content {
      override def isLoginResponse: Boolean = true
      override def loginResponse: scala.Option[com.echo.protocol.Response.LoginResponse] = Some(value)
      override def number: Int = 1002
    }
    @SerialVersionUID(0L)
    case class AuthenticationResponse(value: com.echo.protocol.Response.AuthenticationResponse) extends Content {
      override def isAuthenticationResponse: Boolean = true
      override def authenticationResponse: scala.Option[com.echo.protocol.Response.AuthenticationResponse] = Some(value)
      override def number: Int = 1003
    }
    @SerialVersionUID(0L)
    case class LogoutResponse(value: com.echo.protocol.Response.LogoutResponse) extends Content {
      override def isLogoutResponse: Boolean = true
      override def logoutResponse: scala.Option[com.echo.protocol.Response.LogoutResponse] = Some(value)
      override def number: Int = 1004
    }
    @SerialVersionUID(0L)
    case class QueryUserInfoResponse(value: com.echo.protocol.Response.QueryUserInfoResponse) extends Content {
      override def isQueryUserInfoResponse: Boolean = true
      override def queryUserInfoResponse: scala.Option[com.echo.protocol.Response.QueryUserInfoResponse] = Some(value)
      override def number: Int = 1005
    }
    @SerialVersionUID(0L)
    case class UpdateUsernameResponse(value: com.echo.protocol.Response.UpdateUsernameResponse) extends Content {
      override def isUpdateUsernameResponse: Boolean = true
      override def updateUsernameResponse: scala.Option[com.echo.protocol.Response.UpdateUsernameResponse] = Some(value)
      override def number: Int = 1006
    }
    @SerialVersionUID(0L)
    case class UpdatePhonenumResponse(value: com.echo.protocol.Response.UpdatePhonenumResponse) extends Content {
      override def isUpdatePhonenumResponse: Boolean = true
      override def updatePhonenumResponse: scala.Option[com.echo.protocol.Response.UpdatePhonenumResponse] = Some(value)
      override def number: Int = 1007
    }
    @SerialVersionUID(0L)
    case class UpdateEmailResponse(value: com.echo.protocol.Response.UpdateEmailResponse) extends Content {
      override def isUpdateEmailResponse: Boolean = true
      override def updateEmailResponse: scala.Option[com.echo.protocol.Response.UpdateEmailResponse] = Some(value)
      override def number: Int = 1008
    }
    @SerialVersionUID(0L)
    case class UpdatePasswordResponse(value: com.echo.protocol.Response.UpdatePasswordResponse) extends Content {
      override def isUpdatePasswordResponse: Boolean = true
      override def updatePasswordResponse: scala.Option[com.echo.protocol.Response.UpdatePasswordResponse] = Some(value)
      override def number: Int = 1009
    }
    @SerialVersionUID(0L)
    case class UpdateSecQuestionResponse(value: com.echo.protocol.Response.UpdateSecQuestionResponse) extends Content {
      override def isUpdateSecQuestionResponse: Boolean = true
      override def updateSecQuestionResponse: scala.Option[com.echo.protocol.Response.UpdateSecQuestionResponse] = Some(value)
      override def number: Int = 1010
    }
    @SerialVersionUID(0L)
    case class AddUserAddressReponse(value: com.echo.protocol.Response.AddUserAddressResponse) extends Content {
      override def isAddUserAddressReponse: Boolean = true
      override def addUserAddressReponse: scala.Option[com.echo.protocol.Response.AddUserAddressResponse] = Some(value)
      override def number: Int = 1100
    }
    @SerialVersionUID(0L)
    case class UpdateUserAddressReponse(value: com.echo.protocol.Response.UpdateUserAddressResponse) extends Content {
      override def isUpdateUserAddressReponse: Boolean = true
      override def updateUserAddressReponse: scala.Option[com.echo.protocol.Response.UpdateUserAddressResponse] = Some(value)
      override def number: Int = 1101
    }
    @SerialVersionUID(0L)
    case class DeleteUserAddressReponse(value: com.echo.protocol.Response.DeleteUserAddressResponse) extends Content {
      override def isDeleteUserAddressReponse: Boolean = true
      override def deleteUserAddressReponse: scala.Option[com.echo.protocol.Response.DeleteUserAddressResponse] = Some(value)
      override def number: Int = 1102
    }
  }
  @SerialVersionUID(0L)
  final case class SignupResponse(
      ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[SignupResponse] with com.trueaccord.lenses.Updatable[SignupResponse] {
      @transient
      lazy val serializedSize: Int = {
        var __size = 0
        __size
      }
      def writeTo(output: com.google.protobuf.CodedOutputStream): Unit = {
      }
      def mergeFrom(__input: com.google.protobuf.CodedInputStream): com.echo.protocol.Response.SignupResponse = {
        var _done__ = false
        while (!_done__) {
          val _tag__ = __input.readTag()
          _tag__ match {
            case 0 => _done__ = true
            case tag => __input.skipField(tag)
          }
        }
        com.echo.protocol.Response.SignupResponse(
        )
      }
      def getField(__field: com.google.protobuf.Descriptors.FieldDescriptor): scala.Any = throw new MatchError(__field)
      override def toString: String = com.trueaccord.scalapb.TextFormat.printToUnicodeString(this)
      def companion = com.echo.protocol.Response.SignupResponse
  }
  
  object SignupResponse extends com.trueaccord.scalapb.GeneratedMessageCompanion[SignupResponse] {
    implicit def messageCompanion: com.trueaccord.scalapb.GeneratedMessageCompanion[SignupResponse] = this
    def fromFieldsMap(__fieldsMap: Map[com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): com.echo.protocol.Response.SignupResponse = {
      require(__fieldsMap.keys.forall(_.getContainingType() == descriptor), "FieldDescriptor does not match message type.")
      val __fields = descriptor.getFields
      com.echo.protocol.Response.SignupResponse(
      )
    }
    def descriptor: com.google.protobuf.Descriptors.Descriptor = com.echo.protocol.Response.descriptor.getNestedTypes.get(0)
    def messageCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__field)
    def enumCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__field)
    lazy val defaultInstance = com.echo.protocol.Response.SignupResponse(
    )
    implicit class SignupResponseLens[UpperPB](_l: com.trueaccord.lenses.Lens[UpperPB, SignupResponse]) extends com.trueaccord.lenses.ObjectLens[UpperPB, SignupResponse](_l) {
    }
  }
  
  @SerialVersionUID(0L)
  final case class LoginResponse(
      token: String = "",
      expiresIn: Int = 0,
      userId: String = "",
      username: String = ""
      ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[LoginResponse] with com.trueaccord.lenses.Updatable[LoginResponse] {
      @transient
      lazy val serializedSize: Int = {
        var __size = 0
        if (token != "") { __size += com.google.protobuf.CodedOutputStream.computeStringSize(2, token) }
        if (expiresIn != 0) { __size += com.google.protobuf.CodedOutputStream.computeInt32Size(3, expiresIn) }
        if (userId != "") { __size += com.google.protobuf.CodedOutputStream.computeStringSize(4, userId) }
        if (username != "") { __size += com.google.protobuf.CodedOutputStream.computeStringSize(5, username) }
        __size
      }
      def writeTo(output: com.google.protobuf.CodedOutputStream): Unit = {
        {
          val __v = token
          if (__v != "") {
            output.writeString(2, __v)
          }
        };
        {
          val __v = expiresIn
          if (__v != 0) {
            output.writeInt32(3, __v)
          }
        };
        {
          val __v = userId
          if (__v != "") {
            output.writeString(4, __v)
          }
        };
        {
          val __v = username
          if (__v != "") {
            output.writeString(5, __v)
          }
        };
      }
      def mergeFrom(__input: com.google.protobuf.CodedInputStream): com.echo.protocol.Response.LoginResponse = {
        var __token = this.token
        var __expiresIn = this.expiresIn
        var __userId = this.userId
        var __username = this.username
        var _done__ = false
        while (!_done__) {
          val _tag__ = __input.readTag()
          _tag__ match {
            case 0 => _done__ = true
            case 18 =>
              __token = __input.readString()
            case 24 =>
              __expiresIn = __input.readInt32()
            case 34 =>
              __userId = __input.readString()
            case 42 =>
              __username = __input.readString()
            case tag => __input.skipField(tag)
          }
        }
        com.echo.protocol.Response.LoginResponse(
            token = __token,
            expiresIn = __expiresIn,
            userId = __userId,
            username = __username
        )
      }
      def withToken(__v: String): LoginResponse = copy(token = __v)
      def withExpiresIn(__v: Int): LoginResponse = copy(expiresIn = __v)
      def withUserId(__v: String): LoginResponse = copy(userId = __v)
      def withUsername(__v: String): LoginResponse = copy(username = __v)
      def getField(__field: com.google.protobuf.Descriptors.FieldDescriptor): scala.Any = {
        __field.getNumber match {
          case 2 => {
            val __t = token
            if (__t != "") __t else null
          }
          case 3 => {
            val __t = expiresIn
            if (__t != 0) __t else null
          }
          case 4 => {
            val __t = userId
            if (__t != "") __t else null
          }
          case 5 => {
            val __t = username
            if (__t != "") __t else null
          }
        }
      }
      override def toString: String = com.trueaccord.scalapb.TextFormat.printToUnicodeString(this)
      def companion = com.echo.protocol.Response.LoginResponse
  }
  
  object LoginResponse extends com.trueaccord.scalapb.GeneratedMessageCompanion[LoginResponse] {
    implicit def messageCompanion: com.trueaccord.scalapb.GeneratedMessageCompanion[LoginResponse] = this
    def fromFieldsMap(__fieldsMap: Map[com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): com.echo.protocol.Response.LoginResponse = {
      require(__fieldsMap.keys.forall(_.getContainingType() == descriptor), "FieldDescriptor does not match message type.")
      val __fields = descriptor.getFields
      com.echo.protocol.Response.LoginResponse(
        __fieldsMap.getOrElse(__fields.get(0), "").asInstanceOf[String],
        __fieldsMap.getOrElse(__fields.get(1), 0).asInstanceOf[Int],
        __fieldsMap.getOrElse(__fields.get(2), "").asInstanceOf[String],
        __fieldsMap.getOrElse(__fields.get(3), "").asInstanceOf[String]
      )
    }
    def descriptor: com.google.protobuf.Descriptors.Descriptor = com.echo.protocol.Response.descriptor.getNestedTypes.get(1)
    def messageCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__field)
    def enumCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__field)
    lazy val defaultInstance = com.echo.protocol.Response.LoginResponse(
    )
    implicit class LoginResponseLens[UpperPB](_l: com.trueaccord.lenses.Lens[UpperPB, LoginResponse]) extends com.trueaccord.lenses.ObjectLens[UpperPB, LoginResponse](_l) {
      def token: com.trueaccord.lenses.Lens[UpperPB, String] = field(_.token)((c_, f_) => c_.copy(token = f_))
      def expiresIn: com.trueaccord.lenses.Lens[UpperPB, Int] = field(_.expiresIn)((c_, f_) => c_.copy(expiresIn = f_))
      def userId: com.trueaccord.lenses.Lens[UpperPB, String] = field(_.userId)((c_, f_) => c_.copy(userId = f_))
      def username: com.trueaccord.lenses.Lens[UpperPB, String] = field(_.username)((c_, f_) => c_.copy(username = f_))
    }
    final val TOKEN_FIELD_NUMBER = 2
    final val EXPIRES_IN_FIELD_NUMBER = 3
    final val USER_ID_FIELD_NUMBER = 4
    final val USERNAME_FIELD_NUMBER = 5
  }
  
  @SerialVersionUID(0L)
  final case class AuthenticationResponse(
      isExpired: Boolean = false,
      expiresIn: Int = 0,
      userId: String = "",
      username: String = ""
      ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[AuthenticationResponse] with com.trueaccord.lenses.Updatable[AuthenticationResponse] {
      @transient
      lazy val serializedSize: Int = {
        var __size = 0
        if (isExpired != false) { __size += com.google.protobuf.CodedOutputStream.computeBoolSize(2, isExpired) }
        if (expiresIn != 0) { __size += com.google.protobuf.CodedOutputStream.computeInt32Size(3, expiresIn) }
        if (userId != "") { __size += com.google.protobuf.CodedOutputStream.computeStringSize(4, userId) }
        if (username != "") { __size += com.google.protobuf.CodedOutputStream.computeStringSize(5, username) }
        __size
      }
      def writeTo(output: com.google.protobuf.CodedOutputStream): Unit = {
        {
          val __v = isExpired
          if (__v != false) {
            output.writeBool(2, __v)
          }
        };
        {
          val __v = expiresIn
          if (__v != 0) {
            output.writeInt32(3, __v)
          }
        };
        {
          val __v = userId
          if (__v != "") {
            output.writeString(4, __v)
          }
        };
        {
          val __v = username
          if (__v != "") {
            output.writeString(5, __v)
          }
        };
      }
      def mergeFrom(__input: com.google.protobuf.CodedInputStream): com.echo.protocol.Response.AuthenticationResponse = {
        var __isExpired = this.isExpired
        var __expiresIn = this.expiresIn
        var __userId = this.userId
        var __username = this.username
        var _done__ = false
        while (!_done__) {
          val _tag__ = __input.readTag()
          _tag__ match {
            case 0 => _done__ = true
            case 16 =>
              __isExpired = __input.readBool()
            case 24 =>
              __expiresIn = __input.readInt32()
            case 34 =>
              __userId = __input.readString()
            case 42 =>
              __username = __input.readString()
            case tag => __input.skipField(tag)
          }
        }
        com.echo.protocol.Response.AuthenticationResponse(
            isExpired = __isExpired,
            expiresIn = __expiresIn,
            userId = __userId,
            username = __username
        )
      }
      def withIsExpired(__v: Boolean): AuthenticationResponse = copy(isExpired = __v)
      def withExpiresIn(__v: Int): AuthenticationResponse = copy(expiresIn = __v)
      def withUserId(__v: String): AuthenticationResponse = copy(userId = __v)
      def withUsername(__v: String): AuthenticationResponse = copy(username = __v)
      def getField(__field: com.google.protobuf.Descriptors.FieldDescriptor): scala.Any = {
        __field.getNumber match {
          case 2 => {
            val __t = isExpired
            if (__t != false) __t else null
          }
          case 3 => {
            val __t = expiresIn
            if (__t != 0) __t else null
          }
          case 4 => {
            val __t = userId
            if (__t != "") __t else null
          }
          case 5 => {
            val __t = username
            if (__t != "") __t else null
          }
        }
      }
      override def toString: String = com.trueaccord.scalapb.TextFormat.printToUnicodeString(this)
      def companion = com.echo.protocol.Response.AuthenticationResponse
  }
  
  object AuthenticationResponse extends com.trueaccord.scalapb.GeneratedMessageCompanion[AuthenticationResponse] {
    implicit def messageCompanion: com.trueaccord.scalapb.GeneratedMessageCompanion[AuthenticationResponse] = this
    def fromFieldsMap(__fieldsMap: Map[com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): com.echo.protocol.Response.AuthenticationResponse = {
      require(__fieldsMap.keys.forall(_.getContainingType() == descriptor), "FieldDescriptor does not match message type.")
      val __fields = descriptor.getFields
      com.echo.protocol.Response.AuthenticationResponse(
        __fieldsMap.getOrElse(__fields.get(0), false).asInstanceOf[Boolean],
        __fieldsMap.getOrElse(__fields.get(1), 0).asInstanceOf[Int],
        __fieldsMap.getOrElse(__fields.get(2), "").asInstanceOf[String],
        __fieldsMap.getOrElse(__fields.get(3), "").asInstanceOf[String]
      )
    }
    def descriptor: com.google.protobuf.Descriptors.Descriptor = com.echo.protocol.Response.descriptor.getNestedTypes.get(2)
    def messageCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__field)
    def enumCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__field)
    lazy val defaultInstance = com.echo.protocol.Response.AuthenticationResponse(
    )
    implicit class AuthenticationResponseLens[UpperPB](_l: com.trueaccord.lenses.Lens[UpperPB, AuthenticationResponse]) extends com.trueaccord.lenses.ObjectLens[UpperPB, AuthenticationResponse](_l) {
      def isExpired: com.trueaccord.lenses.Lens[UpperPB, Boolean] = field(_.isExpired)((c_, f_) => c_.copy(isExpired = f_))
      def expiresIn: com.trueaccord.lenses.Lens[UpperPB, Int] = field(_.expiresIn)((c_, f_) => c_.copy(expiresIn = f_))
      def userId: com.trueaccord.lenses.Lens[UpperPB, String] = field(_.userId)((c_, f_) => c_.copy(userId = f_))
      def username: com.trueaccord.lenses.Lens[UpperPB, String] = field(_.username)((c_, f_) => c_.copy(username = f_))
    }
    final val IS_EXPIRED_FIELD_NUMBER = 2
    final val EXPIRES_IN_FIELD_NUMBER = 3
    final val USER_ID_FIELD_NUMBER = 4
    final val USERNAME_FIELD_NUMBER = 5
  }
  
  @SerialVersionUID(0L)
  final case class LogoutResponse(
      ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[LogoutResponse] with com.trueaccord.lenses.Updatable[LogoutResponse] {
      @transient
      lazy val serializedSize: Int = {
        var __size = 0
        __size
      }
      def writeTo(output: com.google.protobuf.CodedOutputStream): Unit = {
      }
      def mergeFrom(__input: com.google.protobuf.CodedInputStream): com.echo.protocol.Response.LogoutResponse = {
        var _done__ = false
        while (!_done__) {
          val _tag__ = __input.readTag()
          _tag__ match {
            case 0 => _done__ = true
            case tag => __input.skipField(tag)
          }
        }
        com.echo.protocol.Response.LogoutResponse(
        )
      }
      def getField(__field: com.google.protobuf.Descriptors.FieldDescriptor): scala.Any = throw new MatchError(__field)
      override def toString: String = com.trueaccord.scalapb.TextFormat.printToUnicodeString(this)
      def companion = com.echo.protocol.Response.LogoutResponse
  }
  
  object LogoutResponse extends com.trueaccord.scalapb.GeneratedMessageCompanion[LogoutResponse] {
    implicit def messageCompanion: com.trueaccord.scalapb.GeneratedMessageCompanion[LogoutResponse] = this
    def fromFieldsMap(__fieldsMap: Map[com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): com.echo.protocol.Response.LogoutResponse = {
      require(__fieldsMap.keys.forall(_.getContainingType() == descriptor), "FieldDescriptor does not match message type.")
      val __fields = descriptor.getFields
      com.echo.protocol.Response.LogoutResponse(
      )
    }
    def descriptor: com.google.protobuf.Descriptors.Descriptor = com.echo.protocol.Response.descriptor.getNestedTypes.get(3)
    def messageCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__field)
    def enumCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__field)
    lazy val defaultInstance = com.echo.protocol.Response.LogoutResponse(
    )
    implicit class LogoutResponseLens[UpperPB](_l: com.trueaccord.lenses.Lens[UpperPB, LogoutResponse]) extends com.trueaccord.lenses.ObjectLens[UpperPB, LogoutResponse](_l) {
    }
  }
  
  @SerialVersionUID(0L)
  final case class QueryUserInfoResponse(
      userId: String = "",
      username: String = "",
      email: String = "",
      phonenum: String = "",
      securityQuestion1: scala.Option[com.echo.protocol.SecurityQuestionPair] = None,
      securityQuestion2: scala.Option[com.echo.protocol.SecurityQuestionPair] = None,
      securityQuestion3: scala.Option[com.echo.protocol.SecurityQuestionPair] = None,
      addressArray: Seq[com.echo.protocol.UserAddress] = Nil
      ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[QueryUserInfoResponse] with com.trueaccord.lenses.Updatable[QueryUserInfoResponse] {
      @transient
      lazy val serializedSize: Int = {
        var __size = 0
        if (userId != "") { __size += com.google.protobuf.CodedOutputStream.computeStringSize(2, userId) }
        if (username != "") { __size += com.google.protobuf.CodedOutputStream.computeStringSize(3, username) }
        if (email != "") { __size += com.google.protobuf.CodedOutputStream.computeStringSize(4, email) }
        if (phonenum != "") { __size += com.google.protobuf.CodedOutputStream.computeStringSize(5, phonenum) }
        if (securityQuestion1.isDefined) { __size += 1 + com.google.protobuf.CodedOutputStream.computeRawVarint32Size(securityQuestion1.get.serializedSize) + securityQuestion1.get.serializedSize }
        if (securityQuestion2.isDefined) { __size += 1 + com.google.protobuf.CodedOutputStream.computeRawVarint32Size(securityQuestion2.get.serializedSize) + securityQuestion2.get.serializedSize }
        if (securityQuestion3.isDefined) { __size += 1 + com.google.protobuf.CodedOutputStream.computeRawVarint32Size(securityQuestion3.get.serializedSize) + securityQuestion3.get.serializedSize }
        addressArray.foreach(addressArray => __size += 2 + com.google.protobuf.CodedOutputStream.computeRawVarint32Size(addressArray.serializedSize) + addressArray.serializedSize)
        __size
      }
      def writeTo(output: com.google.protobuf.CodedOutputStream): Unit = {
        {
          val __v = userId
          if (__v != "") {
            output.writeString(2, __v)
          }
        };
        {
          val __v = username
          if (__v != "") {
            output.writeString(3, __v)
          }
        };
        {
          val __v = email
          if (__v != "") {
            output.writeString(4, __v)
          }
        };
        {
          val __v = phonenum
          if (__v != "") {
            output.writeString(5, __v)
          }
        };
        securityQuestion1.foreach { __v => 
          output.writeTag(6, 2)
          output.writeRawVarint32(__v.serializedSize)
          __v.writeTo(output)
        };
        securityQuestion2.foreach { __v => 
          output.writeTag(7, 2)
          output.writeRawVarint32(__v.serializedSize)
          __v.writeTo(output)
        };
        securityQuestion3.foreach { __v => 
          output.writeTag(8, 2)
          output.writeRawVarint32(__v.serializedSize)
          __v.writeTo(output)
        };
        addressArray.foreach { __v => 
          output.writeTag(20, 2)
          output.writeRawVarint32(__v.serializedSize)
          __v.writeTo(output)
        };
      }
      def mergeFrom(__input: com.google.protobuf.CodedInputStream): com.echo.protocol.Response.QueryUserInfoResponse = {
        var __userId = this.userId
        var __username = this.username
        var __email = this.email
        var __phonenum = this.phonenum
        var __securityQuestion1 = this.securityQuestion1
        var __securityQuestion2 = this.securityQuestion2
        var __securityQuestion3 = this.securityQuestion3
        val __addressArray = (scala.collection.immutable.Vector.newBuilder[com.echo.protocol.UserAddress] ++= this.addressArray)
        var _done__ = false
        while (!_done__) {
          val _tag__ = __input.readTag()
          _tag__ match {
            case 0 => _done__ = true
            case 18 =>
              __userId = __input.readString()
            case 26 =>
              __username = __input.readString()
            case 34 =>
              __email = __input.readString()
            case 42 =>
              __phonenum = __input.readString()
            case 50 =>
              __securityQuestion1 = Some(com.trueaccord.scalapb.LiteParser.readMessage(__input, __securityQuestion1.getOrElse(com.echo.protocol.SecurityQuestionPair.defaultInstance)))
            case 58 =>
              __securityQuestion2 = Some(com.trueaccord.scalapb.LiteParser.readMessage(__input, __securityQuestion2.getOrElse(com.echo.protocol.SecurityQuestionPair.defaultInstance)))
            case 66 =>
              __securityQuestion3 = Some(com.trueaccord.scalapb.LiteParser.readMessage(__input, __securityQuestion3.getOrElse(com.echo.protocol.SecurityQuestionPair.defaultInstance)))
            case 162 =>
              __addressArray += com.trueaccord.scalapb.LiteParser.readMessage(__input, com.echo.protocol.UserAddress.defaultInstance)
            case tag => __input.skipField(tag)
          }
        }
        com.echo.protocol.Response.QueryUserInfoResponse(
            userId = __userId,
            username = __username,
            email = __email,
            phonenum = __phonenum,
            securityQuestion1 = __securityQuestion1,
            securityQuestion2 = __securityQuestion2,
            securityQuestion3 = __securityQuestion3,
            addressArray = __addressArray.result()
        )
      }
      def withUserId(__v: String): QueryUserInfoResponse = copy(userId = __v)
      def withUsername(__v: String): QueryUserInfoResponse = copy(username = __v)
      def withEmail(__v: String): QueryUserInfoResponse = copy(email = __v)
      def withPhonenum(__v: String): QueryUserInfoResponse = copy(phonenum = __v)
      def getSecurityQuestion1: com.echo.protocol.SecurityQuestionPair = securityQuestion1.getOrElse(com.echo.protocol.SecurityQuestionPair.defaultInstance)
      def clearSecurityQuestion1: QueryUserInfoResponse = copy(securityQuestion1 = None)
      def withSecurityQuestion1(__v: com.echo.protocol.SecurityQuestionPair): QueryUserInfoResponse = copy(securityQuestion1 = Some(__v))
      def getSecurityQuestion2: com.echo.protocol.SecurityQuestionPair = securityQuestion2.getOrElse(com.echo.protocol.SecurityQuestionPair.defaultInstance)
      def clearSecurityQuestion2: QueryUserInfoResponse = copy(securityQuestion2 = None)
      def withSecurityQuestion2(__v: com.echo.protocol.SecurityQuestionPair): QueryUserInfoResponse = copy(securityQuestion2 = Some(__v))
      def getSecurityQuestion3: com.echo.protocol.SecurityQuestionPair = securityQuestion3.getOrElse(com.echo.protocol.SecurityQuestionPair.defaultInstance)
      def clearSecurityQuestion3: QueryUserInfoResponse = copy(securityQuestion3 = None)
      def withSecurityQuestion3(__v: com.echo.protocol.SecurityQuestionPair): QueryUserInfoResponse = copy(securityQuestion3 = Some(__v))
      def clearAddressArray = copy(addressArray = Seq.empty)
      def addAddressArray(__vs: com.echo.protocol.UserAddress*): QueryUserInfoResponse = addAllAddressArray(__vs)
      def addAllAddressArray(__vs: TraversableOnce[com.echo.protocol.UserAddress]): QueryUserInfoResponse = copy(addressArray = addressArray ++ __vs)
      def withAddressArray(__v: Seq[com.echo.protocol.UserAddress]): QueryUserInfoResponse = copy(addressArray = __v)
      def getField(__field: com.google.protobuf.Descriptors.FieldDescriptor): scala.Any = {
        __field.getNumber match {
          case 2 => {
            val __t = userId
            if (__t != "") __t else null
          }
          case 3 => {
            val __t = username
            if (__t != "") __t else null
          }
          case 4 => {
            val __t = email
            if (__t != "") __t else null
          }
          case 5 => {
            val __t = phonenum
            if (__t != "") __t else null
          }
          case 6 => securityQuestion1.getOrElse(null)
          case 7 => securityQuestion2.getOrElse(null)
          case 8 => securityQuestion3.getOrElse(null)
          case 20 => addressArray
        }
      }
      override def toString: String = com.trueaccord.scalapb.TextFormat.printToUnicodeString(this)
      def companion = com.echo.protocol.Response.QueryUserInfoResponse
  }
  
  object QueryUserInfoResponse extends com.trueaccord.scalapb.GeneratedMessageCompanion[QueryUserInfoResponse] {
    implicit def messageCompanion: com.trueaccord.scalapb.GeneratedMessageCompanion[QueryUserInfoResponse] = this
    def fromFieldsMap(__fieldsMap: Map[com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): com.echo.protocol.Response.QueryUserInfoResponse = {
      require(__fieldsMap.keys.forall(_.getContainingType() == descriptor), "FieldDescriptor does not match message type.")
      val __fields = descriptor.getFields
      com.echo.protocol.Response.QueryUserInfoResponse(
        __fieldsMap.getOrElse(__fields.get(0), "").asInstanceOf[String],
        __fieldsMap.getOrElse(__fields.get(1), "").asInstanceOf[String],
        __fieldsMap.getOrElse(__fields.get(2), "").asInstanceOf[String],
        __fieldsMap.getOrElse(__fields.get(3), "").asInstanceOf[String],
        __fieldsMap.get(__fields.get(4)).asInstanceOf[scala.Option[com.echo.protocol.SecurityQuestionPair]],
        __fieldsMap.get(__fields.get(5)).asInstanceOf[scala.Option[com.echo.protocol.SecurityQuestionPair]],
        __fieldsMap.get(__fields.get(6)).asInstanceOf[scala.Option[com.echo.protocol.SecurityQuestionPair]],
        __fieldsMap.getOrElse(__fields.get(7), Nil).asInstanceOf[Seq[com.echo.protocol.UserAddress]]
      )
    }
    def descriptor: com.google.protobuf.Descriptors.Descriptor = com.echo.protocol.Response.descriptor.getNestedTypes.get(4)
    def messageCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedMessageCompanion[_] = {
      require(__field.getContainingType() == descriptor, "FieldDescriptor does not match message type.")
      var __out: com.trueaccord.scalapb.GeneratedMessageCompanion[_] = null
      __field.getNumber match {
        case 6 => __out = com.echo.protocol.SecurityQuestionPair
        case 7 => __out = com.echo.protocol.SecurityQuestionPair
        case 8 => __out = com.echo.protocol.SecurityQuestionPair
        case 20 => __out = com.echo.protocol.UserAddress
      }
    __out
    }
    def enumCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__field)
    lazy val defaultInstance = com.echo.protocol.Response.QueryUserInfoResponse(
    )
    implicit class QueryUserInfoResponseLens[UpperPB](_l: com.trueaccord.lenses.Lens[UpperPB, QueryUserInfoResponse]) extends com.trueaccord.lenses.ObjectLens[UpperPB, QueryUserInfoResponse](_l) {
      def userId: com.trueaccord.lenses.Lens[UpperPB, String] = field(_.userId)((c_, f_) => c_.copy(userId = f_))
      def username: com.trueaccord.lenses.Lens[UpperPB, String] = field(_.username)((c_, f_) => c_.copy(username = f_))
      def email: com.trueaccord.lenses.Lens[UpperPB, String] = field(_.email)((c_, f_) => c_.copy(email = f_))
      def phonenum: com.trueaccord.lenses.Lens[UpperPB, String] = field(_.phonenum)((c_, f_) => c_.copy(phonenum = f_))
      def securityQuestion1: com.trueaccord.lenses.Lens[UpperPB, com.echo.protocol.SecurityQuestionPair] = field(_.getSecurityQuestion1)((c_, f_) => c_.copy(securityQuestion1 = Some(f_)))
      def optionalSecurityQuestion1: com.trueaccord.lenses.Lens[UpperPB, scala.Option[com.echo.protocol.SecurityQuestionPair]] = field(_.securityQuestion1)((c_, f_) => c_.copy(securityQuestion1 = f_))
      def securityQuestion2: com.trueaccord.lenses.Lens[UpperPB, com.echo.protocol.SecurityQuestionPair] = field(_.getSecurityQuestion2)((c_, f_) => c_.copy(securityQuestion2 = Some(f_)))
      def optionalSecurityQuestion2: com.trueaccord.lenses.Lens[UpperPB, scala.Option[com.echo.protocol.SecurityQuestionPair]] = field(_.securityQuestion2)((c_, f_) => c_.copy(securityQuestion2 = f_))
      def securityQuestion3: com.trueaccord.lenses.Lens[UpperPB, com.echo.protocol.SecurityQuestionPair] = field(_.getSecurityQuestion3)((c_, f_) => c_.copy(securityQuestion3 = Some(f_)))
      def optionalSecurityQuestion3: com.trueaccord.lenses.Lens[UpperPB, scala.Option[com.echo.protocol.SecurityQuestionPair]] = field(_.securityQuestion3)((c_, f_) => c_.copy(securityQuestion3 = f_))
      def addressArray: com.trueaccord.lenses.Lens[UpperPB, Seq[com.echo.protocol.UserAddress]] = field(_.addressArray)((c_, f_) => c_.copy(addressArray = f_))
    }
    final val USER_ID_FIELD_NUMBER = 2
    final val USERNAME_FIELD_NUMBER = 3
    final val EMAIL_FIELD_NUMBER = 4
    final val PHONENUM_FIELD_NUMBER = 5
    final val SECURITY_QUESTION1_FIELD_NUMBER = 6
    final val SECURITY_QUESTION2_FIELD_NUMBER = 7
    final val SECURITY_QUESTION3_FIELD_NUMBER = 8
    final val ADDRESSARRAY_FIELD_NUMBER = 20
  }
  
  @SerialVersionUID(0L)
  final case class UpdateUsernameResponse(
      ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[UpdateUsernameResponse] with com.trueaccord.lenses.Updatable[UpdateUsernameResponse] {
      @transient
      lazy val serializedSize: Int = {
        var __size = 0
        __size
      }
      def writeTo(output: com.google.protobuf.CodedOutputStream): Unit = {
      }
      def mergeFrom(__input: com.google.protobuf.CodedInputStream): com.echo.protocol.Response.UpdateUsernameResponse = {
        var _done__ = false
        while (!_done__) {
          val _tag__ = __input.readTag()
          _tag__ match {
            case 0 => _done__ = true
            case tag => __input.skipField(tag)
          }
        }
        com.echo.protocol.Response.UpdateUsernameResponse(
        )
      }
      def getField(__field: com.google.protobuf.Descriptors.FieldDescriptor): scala.Any = throw new MatchError(__field)
      override def toString: String = com.trueaccord.scalapb.TextFormat.printToUnicodeString(this)
      def companion = com.echo.protocol.Response.UpdateUsernameResponse
  }
  
  object UpdateUsernameResponse extends com.trueaccord.scalapb.GeneratedMessageCompanion[UpdateUsernameResponse] {
    implicit def messageCompanion: com.trueaccord.scalapb.GeneratedMessageCompanion[UpdateUsernameResponse] = this
    def fromFieldsMap(__fieldsMap: Map[com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): com.echo.protocol.Response.UpdateUsernameResponse = {
      require(__fieldsMap.keys.forall(_.getContainingType() == descriptor), "FieldDescriptor does not match message type.")
      val __fields = descriptor.getFields
      com.echo.protocol.Response.UpdateUsernameResponse(
      )
    }
    def descriptor: com.google.protobuf.Descriptors.Descriptor = com.echo.protocol.Response.descriptor.getNestedTypes.get(5)
    def messageCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__field)
    def enumCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__field)
    lazy val defaultInstance = com.echo.protocol.Response.UpdateUsernameResponse(
    )
    implicit class UpdateUsernameResponseLens[UpperPB](_l: com.trueaccord.lenses.Lens[UpperPB, UpdateUsernameResponse]) extends com.trueaccord.lenses.ObjectLens[UpperPB, UpdateUsernameResponse](_l) {
    }
  }
  
  @SerialVersionUID(0L)
  final case class UpdatePasswordResponse(
      ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[UpdatePasswordResponse] with com.trueaccord.lenses.Updatable[UpdatePasswordResponse] {
      @transient
      lazy val serializedSize: Int = {
        var __size = 0
        __size
      }
      def writeTo(output: com.google.protobuf.CodedOutputStream): Unit = {
      }
      def mergeFrom(__input: com.google.protobuf.CodedInputStream): com.echo.protocol.Response.UpdatePasswordResponse = {
        var _done__ = false
        while (!_done__) {
          val _tag__ = __input.readTag()
          _tag__ match {
            case 0 => _done__ = true
            case tag => __input.skipField(tag)
          }
        }
        com.echo.protocol.Response.UpdatePasswordResponse(
        )
      }
      def getField(__field: com.google.protobuf.Descriptors.FieldDescriptor): scala.Any = throw new MatchError(__field)
      override def toString: String = com.trueaccord.scalapb.TextFormat.printToUnicodeString(this)
      def companion = com.echo.protocol.Response.UpdatePasswordResponse
  }
  
  object UpdatePasswordResponse extends com.trueaccord.scalapb.GeneratedMessageCompanion[UpdatePasswordResponse] {
    implicit def messageCompanion: com.trueaccord.scalapb.GeneratedMessageCompanion[UpdatePasswordResponse] = this
    def fromFieldsMap(__fieldsMap: Map[com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): com.echo.protocol.Response.UpdatePasswordResponse = {
      require(__fieldsMap.keys.forall(_.getContainingType() == descriptor), "FieldDescriptor does not match message type.")
      val __fields = descriptor.getFields
      com.echo.protocol.Response.UpdatePasswordResponse(
      )
    }
    def descriptor: com.google.protobuf.Descriptors.Descriptor = com.echo.protocol.Response.descriptor.getNestedTypes.get(6)
    def messageCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__field)
    def enumCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__field)
    lazy val defaultInstance = com.echo.protocol.Response.UpdatePasswordResponse(
    )
    implicit class UpdatePasswordResponseLens[UpperPB](_l: com.trueaccord.lenses.Lens[UpperPB, UpdatePasswordResponse]) extends com.trueaccord.lenses.ObjectLens[UpperPB, UpdatePasswordResponse](_l) {
    }
  }
  
  @SerialVersionUID(0L)
  final case class UpdatePhonenumResponse(
      ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[UpdatePhonenumResponse] with com.trueaccord.lenses.Updatable[UpdatePhonenumResponse] {
      @transient
      lazy val serializedSize: Int = {
        var __size = 0
        __size
      }
      def writeTo(output: com.google.protobuf.CodedOutputStream): Unit = {
      }
      def mergeFrom(__input: com.google.protobuf.CodedInputStream): com.echo.protocol.Response.UpdatePhonenumResponse = {
        var _done__ = false
        while (!_done__) {
          val _tag__ = __input.readTag()
          _tag__ match {
            case 0 => _done__ = true
            case tag => __input.skipField(tag)
          }
        }
        com.echo.protocol.Response.UpdatePhonenumResponse(
        )
      }
      def getField(__field: com.google.protobuf.Descriptors.FieldDescriptor): scala.Any = throw new MatchError(__field)
      override def toString: String = com.trueaccord.scalapb.TextFormat.printToUnicodeString(this)
      def companion = com.echo.protocol.Response.UpdatePhonenumResponse
  }
  
  object UpdatePhonenumResponse extends com.trueaccord.scalapb.GeneratedMessageCompanion[UpdatePhonenumResponse] {
    implicit def messageCompanion: com.trueaccord.scalapb.GeneratedMessageCompanion[UpdatePhonenumResponse] = this
    def fromFieldsMap(__fieldsMap: Map[com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): com.echo.protocol.Response.UpdatePhonenumResponse = {
      require(__fieldsMap.keys.forall(_.getContainingType() == descriptor), "FieldDescriptor does not match message type.")
      val __fields = descriptor.getFields
      com.echo.protocol.Response.UpdatePhonenumResponse(
      )
    }
    def descriptor: com.google.protobuf.Descriptors.Descriptor = com.echo.protocol.Response.descriptor.getNestedTypes.get(7)
    def messageCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__field)
    def enumCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__field)
    lazy val defaultInstance = com.echo.protocol.Response.UpdatePhonenumResponse(
    )
    implicit class UpdatePhonenumResponseLens[UpperPB](_l: com.trueaccord.lenses.Lens[UpperPB, UpdatePhonenumResponse]) extends com.trueaccord.lenses.ObjectLens[UpperPB, UpdatePhonenumResponse](_l) {
    }
  }
  
  @SerialVersionUID(0L)
  final case class UpdateEmailResponse(
      ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[UpdateEmailResponse] with com.trueaccord.lenses.Updatable[UpdateEmailResponse] {
      @transient
      lazy val serializedSize: Int = {
        var __size = 0
        __size
      }
      def writeTo(output: com.google.protobuf.CodedOutputStream): Unit = {
      }
      def mergeFrom(__input: com.google.protobuf.CodedInputStream): com.echo.protocol.Response.UpdateEmailResponse = {
        var _done__ = false
        while (!_done__) {
          val _tag__ = __input.readTag()
          _tag__ match {
            case 0 => _done__ = true
            case tag => __input.skipField(tag)
          }
        }
        com.echo.protocol.Response.UpdateEmailResponse(
        )
      }
      def getField(__field: com.google.protobuf.Descriptors.FieldDescriptor): scala.Any = throw new MatchError(__field)
      override def toString: String = com.trueaccord.scalapb.TextFormat.printToUnicodeString(this)
      def companion = com.echo.protocol.Response.UpdateEmailResponse
  }
  
  object UpdateEmailResponse extends com.trueaccord.scalapb.GeneratedMessageCompanion[UpdateEmailResponse] {
    implicit def messageCompanion: com.trueaccord.scalapb.GeneratedMessageCompanion[UpdateEmailResponse] = this
    def fromFieldsMap(__fieldsMap: Map[com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): com.echo.protocol.Response.UpdateEmailResponse = {
      require(__fieldsMap.keys.forall(_.getContainingType() == descriptor), "FieldDescriptor does not match message type.")
      val __fields = descriptor.getFields
      com.echo.protocol.Response.UpdateEmailResponse(
      )
    }
    def descriptor: com.google.protobuf.Descriptors.Descriptor = com.echo.protocol.Response.descriptor.getNestedTypes.get(8)
    def messageCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__field)
    def enumCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__field)
    lazy val defaultInstance = com.echo.protocol.Response.UpdateEmailResponse(
    )
    implicit class UpdateEmailResponseLens[UpperPB](_l: com.trueaccord.lenses.Lens[UpperPB, UpdateEmailResponse]) extends com.trueaccord.lenses.ObjectLens[UpperPB, UpdateEmailResponse](_l) {
    }
  }
  
  @SerialVersionUID(0L)
  final case class UpdateSecQuestionResponse(
      ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[UpdateSecQuestionResponse] with com.trueaccord.lenses.Updatable[UpdateSecQuestionResponse] {
      @transient
      lazy val serializedSize: Int = {
        var __size = 0
        __size
      }
      def writeTo(output: com.google.protobuf.CodedOutputStream): Unit = {
      }
      def mergeFrom(__input: com.google.protobuf.CodedInputStream): com.echo.protocol.Response.UpdateSecQuestionResponse = {
        var _done__ = false
        while (!_done__) {
          val _tag__ = __input.readTag()
          _tag__ match {
            case 0 => _done__ = true
            case tag => __input.skipField(tag)
          }
        }
        com.echo.protocol.Response.UpdateSecQuestionResponse(
        )
      }
      def getField(__field: com.google.protobuf.Descriptors.FieldDescriptor): scala.Any = throw new MatchError(__field)
      override def toString: String = com.trueaccord.scalapb.TextFormat.printToUnicodeString(this)
      def companion = com.echo.protocol.Response.UpdateSecQuestionResponse
  }
  
  object UpdateSecQuestionResponse extends com.trueaccord.scalapb.GeneratedMessageCompanion[UpdateSecQuestionResponse] {
    implicit def messageCompanion: com.trueaccord.scalapb.GeneratedMessageCompanion[UpdateSecQuestionResponse] = this
    def fromFieldsMap(__fieldsMap: Map[com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): com.echo.protocol.Response.UpdateSecQuestionResponse = {
      require(__fieldsMap.keys.forall(_.getContainingType() == descriptor), "FieldDescriptor does not match message type.")
      val __fields = descriptor.getFields
      com.echo.protocol.Response.UpdateSecQuestionResponse(
      )
    }
    def descriptor: com.google.protobuf.Descriptors.Descriptor = com.echo.protocol.Response.descriptor.getNestedTypes.get(9)
    def messageCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__field)
    def enumCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__field)
    lazy val defaultInstance = com.echo.protocol.Response.UpdateSecQuestionResponse(
    )
    implicit class UpdateSecQuestionResponseLens[UpperPB](_l: com.trueaccord.lenses.Lens[UpperPB, UpdateSecQuestionResponse]) extends com.trueaccord.lenses.ObjectLens[UpperPB, UpdateSecQuestionResponse](_l) {
    }
  }
  
  @SerialVersionUID(0L)
  final case class AddUserAddressResponse(
      ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[AddUserAddressResponse] with com.trueaccord.lenses.Updatable[AddUserAddressResponse] {
      @transient
      lazy val serializedSize: Int = {
        var __size = 0
        __size
      }
      def writeTo(output: com.google.protobuf.CodedOutputStream): Unit = {
      }
      def mergeFrom(__input: com.google.protobuf.CodedInputStream): com.echo.protocol.Response.AddUserAddressResponse = {
        var _done__ = false
        while (!_done__) {
          val _tag__ = __input.readTag()
          _tag__ match {
            case 0 => _done__ = true
            case tag => __input.skipField(tag)
          }
        }
        com.echo.protocol.Response.AddUserAddressResponse(
        )
      }
      def getField(__field: com.google.protobuf.Descriptors.FieldDescriptor): scala.Any = throw new MatchError(__field)
      override def toString: String = com.trueaccord.scalapb.TextFormat.printToUnicodeString(this)
      def companion = com.echo.protocol.Response.AddUserAddressResponse
  }
  
  object AddUserAddressResponse extends com.trueaccord.scalapb.GeneratedMessageCompanion[AddUserAddressResponse] {
    implicit def messageCompanion: com.trueaccord.scalapb.GeneratedMessageCompanion[AddUserAddressResponse] = this
    def fromFieldsMap(__fieldsMap: Map[com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): com.echo.protocol.Response.AddUserAddressResponse = {
      require(__fieldsMap.keys.forall(_.getContainingType() == descriptor), "FieldDescriptor does not match message type.")
      val __fields = descriptor.getFields
      com.echo.protocol.Response.AddUserAddressResponse(
      )
    }
    def descriptor: com.google.protobuf.Descriptors.Descriptor = com.echo.protocol.Response.descriptor.getNestedTypes.get(10)
    def messageCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__field)
    def enumCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__field)
    lazy val defaultInstance = com.echo.protocol.Response.AddUserAddressResponse(
    )
    implicit class AddUserAddressResponseLens[UpperPB](_l: com.trueaccord.lenses.Lens[UpperPB, AddUserAddressResponse]) extends com.trueaccord.lenses.ObjectLens[UpperPB, AddUserAddressResponse](_l) {
    }
  }
  
  @SerialVersionUID(0L)
  final case class UpdateUserAddressResponse(
      ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[UpdateUserAddressResponse] with com.trueaccord.lenses.Updatable[UpdateUserAddressResponse] {
      @transient
      lazy val serializedSize: Int = {
        var __size = 0
        __size
      }
      def writeTo(output: com.google.protobuf.CodedOutputStream): Unit = {
      }
      def mergeFrom(__input: com.google.protobuf.CodedInputStream): com.echo.protocol.Response.UpdateUserAddressResponse = {
        var _done__ = false
        while (!_done__) {
          val _tag__ = __input.readTag()
          _tag__ match {
            case 0 => _done__ = true
            case tag => __input.skipField(tag)
          }
        }
        com.echo.protocol.Response.UpdateUserAddressResponse(
        )
      }
      def getField(__field: com.google.protobuf.Descriptors.FieldDescriptor): scala.Any = throw new MatchError(__field)
      override def toString: String = com.trueaccord.scalapb.TextFormat.printToUnicodeString(this)
      def companion = com.echo.protocol.Response.UpdateUserAddressResponse
  }
  
  object UpdateUserAddressResponse extends com.trueaccord.scalapb.GeneratedMessageCompanion[UpdateUserAddressResponse] {
    implicit def messageCompanion: com.trueaccord.scalapb.GeneratedMessageCompanion[UpdateUserAddressResponse] = this
    def fromFieldsMap(__fieldsMap: Map[com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): com.echo.protocol.Response.UpdateUserAddressResponse = {
      require(__fieldsMap.keys.forall(_.getContainingType() == descriptor), "FieldDescriptor does not match message type.")
      val __fields = descriptor.getFields
      com.echo.protocol.Response.UpdateUserAddressResponse(
      )
    }
    def descriptor: com.google.protobuf.Descriptors.Descriptor = com.echo.protocol.Response.descriptor.getNestedTypes.get(11)
    def messageCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__field)
    def enumCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__field)
    lazy val defaultInstance = com.echo.protocol.Response.UpdateUserAddressResponse(
    )
    implicit class UpdateUserAddressResponseLens[UpperPB](_l: com.trueaccord.lenses.Lens[UpperPB, UpdateUserAddressResponse]) extends com.trueaccord.lenses.ObjectLens[UpperPB, UpdateUserAddressResponse](_l) {
    }
  }
  
  @SerialVersionUID(0L)
  final case class DeleteUserAddressResponse(
      ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[DeleteUserAddressResponse] with com.trueaccord.lenses.Updatable[DeleteUserAddressResponse] {
      @transient
      lazy val serializedSize: Int = {
        var __size = 0
        __size
      }
      def writeTo(output: com.google.protobuf.CodedOutputStream): Unit = {
      }
      def mergeFrom(__input: com.google.protobuf.CodedInputStream): com.echo.protocol.Response.DeleteUserAddressResponse = {
        var _done__ = false
        while (!_done__) {
          val _tag__ = __input.readTag()
          _tag__ match {
            case 0 => _done__ = true
            case tag => __input.skipField(tag)
          }
        }
        com.echo.protocol.Response.DeleteUserAddressResponse(
        )
      }
      def getField(__field: com.google.protobuf.Descriptors.FieldDescriptor): scala.Any = throw new MatchError(__field)
      override def toString: String = com.trueaccord.scalapb.TextFormat.printToUnicodeString(this)
      def companion = com.echo.protocol.Response.DeleteUserAddressResponse
  }
  
  object DeleteUserAddressResponse extends com.trueaccord.scalapb.GeneratedMessageCompanion[DeleteUserAddressResponse] {
    implicit def messageCompanion: com.trueaccord.scalapb.GeneratedMessageCompanion[DeleteUserAddressResponse] = this
    def fromFieldsMap(__fieldsMap: Map[com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): com.echo.protocol.Response.DeleteUserAddressResponse = {
      require(__fieldsMap.keys.forall(_.getContainingType() == descriptor), "FieldDescriptor does not match message type.")
      val __fields = descriptor.getFields
      com.echo.protocol.Response.DeleteUserAddressResponse(
      )
    }
    def descriptor: com.google.protobuf.Descriptors.Descriptor = com.echo.protocol.Response.descriptor.getNestedTypes.get(12)
    def messageCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__field)
    def enumCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__field)
    lazy val defaultInstance = com.echo.protocol.Response.DeleteUserAddressResponse(
    )
    implicit class DeleteUserAddressResponseLens[UpperPB](_l: com.trueaccord.lenses.Lens[UpperPB, DeleteUserAddressResponse]) extends com.trueaccord.lenses.ObjectLens[UpperPB, DeleteUserAddressResponse](_l) {
    }
  }
  
  implicit class ResponseLens[UpperPB](_l: com.trueaccord.lenses.Lens[UpperPB, Response]) extends com.trueaccord.lenses.ObjectLens[UpperPB, Response](_l) {
    def result: com.trueaccord.lenses.Lens[UpperPB, com.echo.protocol.ResultCode] = field(_.result)((c_, f_) => c_.copy(result = f_))
    def errorDescription: com.trueaccord.lenses.Lens[UpperPB, String] = field(_.errorDescription)((c_, f_) => c_.copy(errorDescription = f_))
    def signupResponse: com.trueaccord.lenses.Lens[UpperPB, com.echo.protocol.Response.SignupResponse] = field(_.getSignupResponse)((c_, f_) => c_.copy(content = com.echo.protocol.Response.Content.SignupResponse(f_)))
    def loginResponse: com.trueaccord.lenses.Lens[UpperPB, com.echo.protocol.Response.LoginResponse] = field(_.getLoginResponse)((c_, f_) => c_.copy(content = com.echo.protocol.Response.Content.LoginResponse(f_)))
    def authenticationResponse: com.trueaccord.lenses.Lens[UpperPB, com.echo.protocol.Response.AuthenticationResponse] = field(_.getAuthenticationResponse)((c_, f_) => c_.copy(content = com.echo.protocol.Response.Content.AuthenticationResponse(f_)))
    def logoutResponse: com.trueaccord.lenses.Lens[UpperPB, com.echo.protocol.Response.LogoutResponse] = field(_.getLogoutResponse)((c_, f_) => c_.copy(content = com.echo.protocol.Response.Content.LogoutResponse(f_)))
    def queryUserInfoResponse: com.trueaccord.lenses.Lens[UpperPB, com.echo.protocol.Response.QueryUserInfoResponse] = field(_.getQueryUserInfoResponse)((c_, f_) => c_.copy(content = com.echo.protocol.Response.Content.QueryUserInfoResponse(f_)))
    def updateUsernameResponse: com.trueaccord.lenses.Lens[UpperPB, com.echo.protocol.Response.UpdateUsernameResponse] = field(_.getUpdateUsernameResponse)((c_, f_) => c_.copy(content = com.echo.protocol.Response.Content.UpdateUsernameResponse(f_)))
    def updatePhonenumResponse: com.trueaccord.lenses.Lens[UpperPB, com.echo.protocol.Response.UpdatePhonenumResponse] = field(_.getUpdatePhonenumResponse)((c_, f_) => c_.copy(content = com.echo.protocol.Response.Content.UpdatePhonenumResponse(f_)))
    def updateEmailResponse: com.trueaccord.lenses.Lens[UpperPB, com.echo.protocol.Response.UpdateEmailResponse] = field(_.getUpdateEmailResponse)((c_, f_) => c_.copy(content = com.echo.protocol.Response.Content.UpdateEmailResponse(f_)))
    def updatePasswordResponse: com.trueaccord.lenses.Lens[UpperPB, com.echo.protocol.Response.UpdatePasswordResponse] = field(_.getUpdatePasswordResponse)((c_, f_) => c_.copy(content = com.echo.protocol.Response.Content.UpdatePasswordResponse(f_)))
    def updateSecQuestionResponse: com.trueaccord.lenses.Lens[UpperPB, com.echo.protocol.Response.UpdateSecQuestionResponse] = field(_.getUpdateSecQuestionResponse)((c_, f_) => c_.copy(content = com.echo.protocol.Response.Content.UpdateSecQuestionResponse(f_)))
    def addUserAddressReponse: com.trueaccord.lenses.Lens[UpperPB, com.echo.protocol.Response.AddUserAddressResponse] = field(_.getAddUserAddressReponse)((c_, f_) => c_.copy(content = com.echo.protocol.Response.Content.AddUserAddressReponse(f_)))
    def updateUserAddressReponse: com.trueaccord.lenses.Lens[UpperPB, com.echo.protocol.Response.UpdateUserAddressResponse] = field(_.getUpdateUserAddressReponse)((c_, f_) => c_.copy(content = com.echo.protocol.Response.Content.UpdateUserAddressReponse(f_)))
    def deleteUserAddressReponse: com.trueaccord.lenses.Lens[UpperPB, com.echo.protocol.Response.DeleteUserAddressResponse] = field(_.getDeleteUserAddressReponse)((c_, f_) => c_.copy(content = com.echo.protocol.Response.Content.DeleteUserAddressReponse(f_)))
    def content: com.trueaccord.lenses.Lens[UpperPB, com.echo.protocol.Response.Content] = field(_.content)((c_, f_) => c_.copy(content = f_))
  }
  final val RESULT_FIELD_NUMBER = 1
  final val ERROR_DESCRIPTION_FIELD_NUMBER = 2
  final val SIGNUP_RESPONSE_FIELD_NUMBER = 1001
  final val LOGIN_RESPONSE_FIELD_NUMBER = 1002
  final val AUTHENTICATION_RESPONSE_FIELD_NUMBER = 1003
  final val LOGOUT_RESPONSE_FIELD_NUMBER = 1004
  final val QUERY_USER_INFO_RESPONSE_FIELD_NUMBER = 1005
  final val UPDATE_USERNAME_RESPONSE_FIELD_NUMBER = 1006
  final val UPDATE_PHONENUM_RESPONSE_FIELD_NUMBER = 1007
  final val UPDATE_EMAIL_RESPONSE_FIELD_NUMBER = 1008
  final val UPDATE_PASSWORD_RESPONSE_FIELD_NUMBER = 1009
  final val UPDATE_SEC_QUESTION_RESPONSE_FIELD_NUMBER = 1010
  final val ADD_USER_ADDRESS_REPONSE_FIELD_NUMBER = 1100
  final val UPDATE_USER_ADDRESS_REPONSE_FIELD_NUMBER = 1101
  final val DELETE_USER_ADDRESS_REPONSE_FIELD_NUMBER = 1102
}
