// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.echo.protocol.gold



sealed trait OrderState extends com.trueaccord.scalapb.GeneratedEnum {
  type EnumType = OrderState
  def isOrderStateEmpty: Boolean = false
  def isUnpay: Boolean = false
  def isPaySuccess: Boolean = false
  def isPayError: Boolean = false
  def isDeliver: Boolean = false
  def isDeliverConfirm: Boolean = false
  def isRefund: Boolean = false
  def isRefundConfirm: Boolean = false
  def isCancelled: Boolean = false
  def isUnrecognized: Boolean = false
  def companion: com.trueaccord.scalapb.GeneratedEnumCompanion[OrderState] = OrderState
}

object OrderState extends com.trueaccord.scalapb.GeneratedEnumCompanion[OrderState] {
  implicit def enumCompanion: com.trueaccord.scalapb.GeneratedEnumCompanion[OrderState] = this
  @SerialVersionUID(0L)
  case object ORDER_STATE_EMPTY extends OrderState {
    val value = 0
    val index = 0
    val name = "ORDER_STATE_EMPTY"
    override def isOrderStateEmpty: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object UNPAY extends OrderState {
    val value = 1
    val index = 1
    val name = "UNPAY"
    override def isUnpay: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object PAY_SUCCESS extends OrderState {
    val value = 2
    val index = 2
    val name = "PAY_SUCCESS"
    override def isPaySuccess: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object PAY_ERROR extends OrderState {
    val value = 3
    val index = 3
    val name = "PAY_ERROR"
    override def isPayError: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object DELIVER extends OrderState {
    val value = 4
    val index = 4
    val name = "DELIVER"
    override def isDeliver: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object DELIVER_CONFIRM extends OrderState {
    val value = 5
    val index = 5
    val name = "DELIVER_CONFIRM"
    override def isDeliverConfirm: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object REFUND extends OrderState {
    val value = 6
    val index = 6
    val name = "REFUND"
    override def isRefund: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object REFUND_CONFIRM extends OrderState {
    val value = 7
    val index = 7
    val name = "REFUND_CONFIRM"
    override def isRefundConfirm: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object CANCELLED extends OrderState {
    val value = 8
    val index = 8
    val name = "CANCELLED"
    override def isCancelled: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case class Unrecognized(value: Int) extends OrderState {
    val name = "UNRECOGNIZED"
    val index = -1
    override def isUnrecognized: Boolean = true
  }
  
  lazy val values = scala.collection.Seq(ORDER_STATE_EMPTY, UNPAY, PAY_SUCCESS, PAY_ERROR, DELIVER, DELIVER_CONFIRM, REFUND, REFUND_CONFIRM, CANCELLED)
  def fromValue(value: Int): OrderState = value match {
    case 0 => ORDER_STATE_EMPTY
    case 1 => UNPAY
    case 2 => PAY_SUCCESS
    case 3 => PAY_ERROR
    case 4 => DELIVER
    case 5 => DELIVER_CONFIRM
    case 6 => REFUND
    case 7 => REFUND_CONFIRM
    case 8 => CANCELLED
    case __other => Unrecognized(__other)
  }
  def descriptor: com.google.protobuf.Descriptors.EnumDescriptor = GoldProto.descriptor.getEnumTypes.get(2)
}