// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.echo.protocol.gold



sealed trait PayMethod extends com.trueaccord.scalapb.GeneratedEnum {
  type EnumType = PayMethod
  def isPayMethodEmpty: Boolean = false
  def isOnline: Boolean = false
  def isCod: Boolean = false
  def isUnrecognized: Boolean = false
  def companion: com.trueaccord.scalapb.GeneratedEnumCompanion[PayMethod] = PayMethod
}

object PayMethod extends com.trueaccord.scalapb.GeneratedEnumCompanion[PayMethod] {
  implicit def enumCompanion: com.trueaccord.scalapb.GeneratedEnumCompanion[PayMethod] = this
  @SerialVersionUID(0L)
  case object PAY_METHOD_EMPTY extends PayMethod {
    val value = 0
    val index = 0
    val name = "PAY_METHOD_EMPTY"
    override def isPayMethodEmpty: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object ONLINE extends PayMethod {
    val value = 1
    val index = 1
    val name = "ONLINE"
    override def isOnline: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object COD extends PayMethod {
    val value = 2
    val index = 2
    val name = "COD"
    override def isCod: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case class Unrecognized(value: Int) extends PayMethod {
    val name = "UNRECOGNIZED"
    val index = -1
    override def isUnrecognized: Boolean = true
  }
  
  lazy val values = Seq(PAY_METHOD_EMPTY, ONLINE, COD)
  def fromValue(value: Int): PayMethod = value match {
    case 0 => PAY_METHOD_EMPTY
    case 1 => ONLINE
    case 2 => COD
    case __other => Unrecognized(__other)
  }
  def descriptor: com.google.protobuf.Descriptors.EnumDescriptor = GoldProto.descriptor.getEnumTypes.get(0)
}