// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.echo.protocol.captain



/** 购物车条目
  *
  * @param productId
  *  商品ID
  * @param num
  *  商品数量
  * @param createAt
  *   创建时间
  * @param updateAt
  *   最后更新时间
  */
@SerialVersionUID(0L)
final case class CartItem(
    productId: String = "",
    num: Int = 0,
    createAt: Long = 0L,
    updateAt: Long = 0L
    ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[CartItem] with com.trueaccord.lenses.Updatable[CartItem] {
    @transient
    private[this] var __serializedSizeCachedValue: Int = 0
    private[this] def __computeSerializedValue(): Int = {
      var __size = 0
      if (productId != "") { __size += com.google.protobuf.CodedOutputStream.computeStringSize(1, productId) }
      if (num != 0) { __size += com.google.protobuf.CodedOutputStream.computeInt32Size(2, num) }
      if (createAt != 0L) { __size += com.google.protobuf.CodedOutputStream.computeInt64Size(10, createAt) }
      if (updateAt != 0L) { __size += com.google.protobuf.CodedOutputStream.computeInt64Size(11, updateAt) }
      __size
    }
    final override def serializedSize: Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: com.google.protobuf.CodedOutputStream): Unit = {
      {
        val __v = productId
        if (__v != "") {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = num
        if (__v != 0) {
          _output__.writeInt32(2, __v)
        }
      };
      {
        val __v = createAt
        if (__v != 0L) {
          _output__.writeInt64(10, __v)
        }
      };
      {
        val __v = updateAt
        if (__v != 0L) {
          _output__.writeInt64(11, __v)
        }
      };
    }
    def mergeFrom(`_input__`: com.google.protobuf.CodedInputStream): com.echo.protocol.captain.CartItem = {
      var __productId = this.productId
      var __num = this.num
      var __createAt = this.createAt
      var __updateAt = this.updateAt
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __productId = _input__.readString()
          case 16 =>
            __num = _input__.readInt32()
          case 80 =>
            __createAt = _input__.readInt64()
          case 88 =>
            __updateAt = _input__.readInt64()
          case tag => _input__.skipField(tag)
        }
      }
      com.echo.protocol.captain.CartItem(
          productId = __productId,
          num = __num,
          createAt = __createAt,
          updateAt = __updateAt
      )
    }
    def withProductId(__v: String): CartItem = copy(productId = __v)
    def withNum(__v: Int): CartItem = copy(num = __v)
    def withCreateAt(__v: Long): CartItem = copy(createAt = __v)
    def withUpdateAt(__v: Long): CartItem = copy(updateAt = __v)
    def getField(__field: com.google.protobuf.Descriptors.FieldDescriptor): scala.Any = {
      __field.getNumber match {
        case 1 => {
          val __t = productId
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = num
          if (__t != 0) __t else null
        }
        case 10 => {
          val __t = createAt
          if (__t != 0L) __t else null
        }
        case 11 => {
          val __t = updateAt
          if (__t != 0L) __t else null
        }
      }
    }
    override def toString: String = com.trueaccord.scalapb.TextFormat.printToUnicodeString(this)
    def companion = com.echo.protocol.captain.CartItem
}

object CartItem extends com.trueaccord.scalapb.GeneratedMessageCompanion[com.echo.protocol.captain.CartItem] {
  implicit def messageCompanion: com.trueaccord.scalapb.GeneratedMessageCompanion[com.echo.protocol.captain.CartItem] = this
  def fromFieldsMap(__fieldsMap: scala.collection.immutable.Map[com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): com.echo.protocol.captain.CartItem = {
    require(__fieldsMap.keys.forall(_.getContainingType() == descriptor), "FieldDescriptor does not match message type.")
    val __fields = descriptor.getFields
    com.echo.protocol.captain.CartItem(
      __fieldsMap.getOrElse(__fields.get(0), "").asInstanceOf[String],
      __fieldsMap.getOrElse(__fields.get(1), 0).asInstanceOf[Int],
      __fieldsMap.getOrElse(__fields.get(2), 0L).asInstanceOf[Long],
      __fieldsMap.getOrElse(__fields.get(3), 0L).asInstanceOf[Long]
    )
  }
  def descriptor: com.google.protobuf.Descriptors.Descriptor = CaptainProto.descriptor.getMessageTypes.get(0)
  def messageCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__field)
  def enumCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__field)
  lazy val defaultInstance = com.echo.protocol.captain.CartItem(
  )
  implicit class CartItemLens[UpperPB](_l: com.trueaccord.lenses.Lens[UpperPB, com.echo.protocol.captain.CartItem]) extends com.trueaccord.lenses.ObjectLens[UpperPB, com.echo.protocol.captain.CartItem](_l) {
    def productId: com.trueaccord.lenses.Lens[UpperPB, String] = field(_.productId)((c_, f_) => c_.copy(productId = f_))
    def num: com.trueaccord.lenses.Lens[UpperPB, Int] = field(_.num)((c_, f_) => c_.copy(num = f_))
    def createAt: com.trueaccord.lenses.Lens[UpperPB, Long] = field(_.createAt)((c_, f_) => c_.copy(createAt = f_))
    def updateAt: com.trueaccord.lenses.Lens[UpperPB, Long] = field(_.updateAt)((c_, f_) => c_.copy(updateAt = f_))
  }
  final val PRODUCT_ID_FIELD_NUMBER = 1
  final val NUM_FIELD_NUMBER = 2
  final val CREATE_AT_FIELD_NUMBER = 10
  final val UPDATE_AT_FIELD_NUMBER = 11
}
