// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.echo.protocol.captain



@SerialVersionUID(0L)
final case class QueryUserInfoRequest(
    token: String = "",
    fields: scala.collection.Seq[String] = Nil
    ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[QueryUserInfoRequest] with com.trueaccord.lenses.Updatable[QueryUserInfoRequest] {
    @transient
    private[this] var __serializedSizeCachedValue: Int = 0
    private[this] def __computeSerializedValue(): Int = {
      var __size = 0
      if (token != "") { __size += com.google.protobuf.CodedOutputStream.computeStringSize(1, token) }
      fields.foreach(fields => __size += com.google.protobuf.CodedOutputStream.computeStringSize(2, fields))
      __size
    }
    final override def serializedSize: Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: com.google.protobuf.CodedOutputStream): Unit = {
      {
        val __v = token
        if (__v != "") {
          _output__.writeString(1, __v)
        }
      };
      fields.foreach { __v =>
        _output__.writeString(2, __v)
      };
    }
    def mergeFrom(`_input__`: com.google.protobuf.CodedInputStream): com.echo.protocol.captain.QueryUserInfoRequest = {
      var __token = this.token
      val __fields = (scala.collection.immutable.Vector.newBuilder[String] ++= this.fields)
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __token = _input__.readString()
          case 18 =>
            __fields += _input__.readString()
          case tag => _input__.skipField(tag)
        }
      }
      com.echo.protocol.captain.QueryUserInfoRequest(
          token = __token,
          fields = __fields.result()
      )
    }
    def withToken(__v: String): QueryUserInfoRequest = copy(token = __v)
    def clearFields = copy(fields = scala.collection.Seq.empty)
    def addFields(__vs: String*): QueryUserInfoRequest = addAllFields(__vs)
    def addAllFields(__vs: TraversableOnce[String]): QueryUserInfoRequest = copy(fields = fields ++ __vs)
    def withFields(__v: scala.collection.Seq[String]): QueryUserInfoRequest = copy(fields = __v)
    def getField(__field: com.google.protobuf.Descriptors.FieldDescriptor): scala.Any = {
      __field.getNumber match {
        case 1 => {
          val __t = token
          if (__t != "") __t else null
        }
        case 2 => fields
      }
    }
    override def toString: String = com.trueaccord.scalapb.TextFormat.printToUnicodeString(this)
    def companion = com.echo.protocol.captain.QueryUserInfoRequest
}

object QueryUserInfoRequest extends com.trueaccord.scalapb.GeneratedMessageCompanion[com.echo.protocol.captain.QueryUserInfoRequest] {
  implicit def messageCompanion: com.trueaccord.scalapb.GeneratedMessageCompanion[com.echo.protocol.captain.QueryUserInfoRequest] = this
  def fromFieldsMap(__fieldsMap: scala.collection.immutable.Map[com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): com.echo.protocol.captain.QueryUserInfoRequest = {
    require(__fieldsMap.keys.forall(_.getContainingType() == descriptor), "FieldDescriptor does not match message type.")
    val __fields = descriptor.getFields
    com.echo.protocol.captain.QueryUserInfoRequest(
      __fieldsMap.getOrElse(__fields.get(0), "").asInstanceOf[String],
      __fieldsMap.getOrElse(__fields.get(1), Nil).asInstanceOf[scala.collection.Seq[String]]
    )
  }
  def descriptor: com.google.protobuf.Descriptors.Descriptor = CaptainProto.descriptor.getMessageTypes.get(7)
  def messageCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__field)
  def enumCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__field)
  lazy val defaultInstance = com.echo.protocol.captain.QueryUserInfoRequest(
  )
  implicit class QueryUserInfoRequestLens[UpperPB](_l: com.trueaccord.lenses.Lens[UpperPB, com.echo.protocol.captain.QueryUserInfoRequest]) extends com.trueaccord.lenses.ObjectLens[UpperPB, com.echo.protocol.captain.QueryUserInfoRequest](_l) {
    def token: com.trueaccord.lenses.Lens[UpperPB, String] = field(_.token)((c_, f_) => c_.copy(token = f_))
    def fields: com.trueaccord.lenses.Lens[UpperPB, scala.collection.Seq[String]] = field(_.fields)((c_, f_) => c_.copy(fields = f_))
  }
  final val TOKEN_FIELD_NUMBER = 1
  final val FIELDS_FIELD_NUMBER = 2
}
