// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.echo.protocol.product



object ProductProto {
  lazy val descriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """Cg1wcm9kdWN0LnByb3RvEhljb20uZWNoby5wcm90b2NvbC5wcm9kdWN0Ggxjb21tb24ucHJvdG8imgEKCEl0ZW1JbmZvEhUKB
  nNrdV9pZBgCIAEoCVIFc2t1SWQSEAoDbnVtGAMgASgFUgNudW0SFAoFcHJpY2UYBCABKAFSBXByaWNlEh0KCnJlYWxfcHJpY2UYB
  SABKAFSCXJlYWxQcmljZRIaCghkaXNjb3VudBgGIAEoAVIIZGlzY291bnQSFAoFdG90YWwYByABKAFSBXRvdGFsYgZwcm90bzM="""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
  com.echo.protocol.common.CommonProto.descriptor
    ))
  }
}