// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.echo.protocol.common



object CommonProto {
  lazy val descriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """Cgxjb21tb24ucHJvdG8SGGNvbS5lY2hvLnByb3RvY29sLmNvbW1vbiJ9Cg5SZXNwb25zZUhlYWRlchI8CgZyZXN1bHQYASABK
  A4yJC5jb20uZWNoby5wcm90b2NvbC5jb21tb24uUmVzdWx0Q29kZVIGcmVzdWx0Ei0KEnJlc3VsdF9kZXNjcmlwdGlvbhgCIAEoC
  VIRcmVzdWx0RGVzY3JpcHRpb24q3AIKClJlc3VsdENvZGUSFQoRUkVTVUxUX0NPREVfRU1QVFkQABILCgdTVUNDRVNTEAESGgoVS
  U5URVJOQUxfU0VSVkVSX0VSUk9SEJBOEh4KGElOVkFMSURfUkVRVUVTVF9BUkdVTUVOVBChnAESFwoRT1JERVJfTk9UX0VYSVNUR
  UQQseoBEhkKE0lOVkFMSURfT1JERVJfU1RBVEUQsuoBEhYKEElOVkFMSURfUEhPTkVOVU0QwbgCEhMKDUlOVkFMSURfRU1BSUwQw
  rgCEh4KGFBIT05FTlVNX0FMUkVBRFlfRVhJU1RFRBDFuAISGwoVRU1BSUxfQUxSRUFEWV9FWElTVEVEEMa4AhIWChBJTlZBTElEX
  1BBU1NXT1JEEMu4AhIbChVJTlZBTElEX1NFU1NJT05fVE9LRU4Q0YYDEhsKFVNFU1NJT05fVE9LRU5fRVhQSVJFRBDShgNiBnByb
  3RvMw=="""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
}