// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.echo.protocol.common



object CommonProto {
  lazy val descriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(Seq(
  """Cgxjb21tb24ucHJvdG8SGGNvbS5lY2hvLnByb3RvY29sLmNvbW1vbhoJYW55LnByb3RvIn0KDlJlc3BvbnNlSGVhZGVyEjwKB
  nJlc3VsdBgBIAEoDjIkLmNvbS5lY2hvLnByb3RvY29sLmNvbW1vbi5SZXN1bHRDb2RlUgZyZXN1bHQSLQoScmVzdWx0X2Rlc2Nya
  XB0aW9uGAIgASgJUhFyZXN1bHREZXNjcmlwdGlvbiJHCgdLVkZpZWxkEhAKA2tleRgBIAEoCVIDa2V5EioKBXZhbHVlGAIgASgLM
  hQuZ29vZ2xlLnByb3RvYnVmLkFueVIFdmFsdWUq9AIKClJlc3VsdENvZGUSFQoRUkVTVUxUX0NPREVfRU1QVFkQABILCgdTVUNDR
  VNTEAESGgoVSU5URVJOQUxfU0VSVkVSX0VSUk9SEJBOEh4KGElOVkFMSURfUkVRVUVTVF9BUkdVTUVOVBChnAESFwoRT1JERVJfT
  k9UX0VYSVNURUQQseoBEhkKE0lOVkFMSURfT1JERVJfU1RBVEUQsuoBEhYKEElOVkFMSURfUEhPTkVOVU0QwbgCEhMKDUlOVkFMS
  URfRU1BSUwQwrgCEh4KGFBIT05FTlVNX0FMUkVBRFlfRVhJU1RFRBDFuAISGwoVRU1BSUxfQUxSRUFEWV9FWElTVEVEEMa4AhIWC
  hBJTlZBTElEX1BBU1NXT1JEEMu4AhIbChVJTlZBTElEX1NFU1NJT05fVE9LRU4Q0YYDEhsKFVNFU1NJT05fVE9LRU5fRVhQSVJFR
  BDShgMSFgoQSUxMRUdBTF9BUkdVTUVOVBDh1ANiBnByb3RvMw=="""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
  com.google.protobuf.AnyProto.descriptor
    ))
  }
}