// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.echo.protocol.common



object CommonProto {
  lazy val descriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """Cgxjb21tb24ucHJvdG8SGGNvbS5lY2hvLnByb3RvY29sLmNvbW1vbhoZZ29vZ2xlL3Byb3RvYnVmL2FueS5wcm90byJ9Cg5SZ
  XNwb25zZUhlYWRlchI8CgZyZXN1bHQYASABKA4yJC5jb20uZWNoby5wcm90b2NvbC5jb21tb24uUmVzdWx0Q29kZVIGcmVzdWx0E
  i0KEnJlc3VsdF9kZXNjcmlwdGlvbhgCIAEoCVIRcmVzdWx0RGVzY3JpcHRpb24iRwoHS1ZGaWVsZBIQCgNrZXkYASABKAlSA2tle
  RIqCgV2YWx1ZRgCIAEoCzIULmdvb2dsZS5wcm90b2J1Zi5BbnlSBXZhbHVlKtwCCgpSZXN1bHRDb2RlEhUKEVJFU1VMVF9DT0RFX
  0VNUFRZEAASCwoHU1VDQ0VTUxABEhoKFUlOVEVSTkFMX1NFUlZFUl9FUlJPUhCQThIeChhJTlZBTElEX1JFUVVFU1RfQVJHVU1FT
  lQQoZwBEhcKEU9SREVSX05PVF9FWElTVEVEELHqARIZChNJTlZBTElEX09SREVSX1NUQVRFELLqARIWChBJTlZBTElEX1BIT05FT
  lVNEMG4AhITCg1JTlZBTElEX0VNQUlMEMK4AhIeChhQSE9ORU5VTV9BTFJFQURZX0VYSVNURUQQxbgCEhsKFUVNQUlMX0FMUkVBR
  FlfRVhJU1RFRBDGuAISFgoQSU5WQUxJRF9QQVNTV09SRBDLuAISGwoVSU5WQUxJRF9TRVNTSU9OX1RPS0VOENGGAxIbChVTRVNTS
  U9OX1RPS0VOX0VYUElSRUQQ0oYDYgZwcm90bzM="""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
  com.google.protobuf.any.AnyProto.descriptor
    ))
  }
}