// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.echo.protocol.common



sealed trait ResultCode extends com.trueaccord.scalapb.GeneratedEnum {
  type EnumType = ResultCode
  def isResultCodeEmpty: Boolean = false
  def isSuccess: Boolean = false
  def isInternalServerError: Boolean = false
  def isInvalidRequestArgument: Boolean = false
  def isOrderNotExisted: Boolean = false
  def isInvalidOrderState: Boolean = false
  def isInvalidPhonenum: Boolean = false
  def isInvalidEmail: Boolean = false
  def isPhonenumAlreadyExisted: Boolean = false
  def isEmailAlreadyExisted: Boolean = false
  def isInvalidPassword: Boolean = false
  def isInvalidSessionToken: Boolean = false
  def isSessionTokenExpired: Boolean = false
  def isIllegalArgument: Boolean = false
  def isUnrecognized: Boolean = false
  def companion: com.trueaccord.scalapb.GeneratedEnumCompanion[ResultCode] = ResultCode
}

object ResultCode extends com.trueaccord.scalapb.GeneratedEnumCompanion[ResultCode] {
  implicit def enumCompanion: com.trueaccord.scalapb.GeneratedEnumCompanion[ResultCode] = this
  @SerialVersionUID(0L)
  case object RESULT_CODE_EMPTY extends ResultCode {
    val value = 0
    val index = 0
    val name = "RESULT_CODE_EMPTY"
    override def isResultCodeEmpty: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object SUCCESS extends ResultCode {
    val value = 1
    val index = 1
    val name = "SUCCESS"
    override def isSuccess: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object INTERNAL_SERVER_ERROR extends ResultCode {
    val value = 10000
    val index = 2
    val name = "INTERNAL_SERVER_ERROR"
    override def isInternalServerError: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object INVALID_REQUEST_ARGUMENT extends ResultCode {
    val value = 20001
    val index = 3
    val name = "INVALID_REQUEST_ARGUMENT"
    override def isInvalidRequestArgument: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object ORDER_NOT_EXISTED extends ResultCode {
    val value = 30001
    val index = 4
    val name = "ORDER_NOT_EXISTED"
    override def isOrderNotExisted: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object INVALID_ORDER_STATE extends ResultCode {
    val value = 30002
    val index = 5
    val name = "INVALID_ORDER_STATE"
    override def isInvalidOrderState: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object INVALID_PHONENUM extends ResultCode {
    val value = 40001
    val index = 6
    val name = "INVALID_PHONENUM"
    override def isInvalidPhonenum: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object INVALID_EMAIL extends ResultCode {
    val value = 40002
    val index = 7
    val name = "INVALID_EMAIL"
    override def isInvalidEmail: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object PHONENUM_ALREADY_EXISTED extends ResultCode {
    val value = 40005
    val index = 8
    val name = "PHONENUM_ALREADY_EXISTED"
    override def isPhonenumAlreadyExisted: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object EMAIL_ALREADY_EXISTED extends ResultCode {
    val value = 40006
    val index = 9
    val name = "EMAIL_ALREADY_EXISTED"
    override def isEmailAlreadyExisted: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object INVALID_PASSWORD extends ResultCode {
    val value = 40011
    val index = 10
    val name = "INVALID_PASSWORD"
    override def isInvalidPassword: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object INVALID_SESSION_TOKEN extends ResultCode {
    val value = 50001
    val index = 11
    val name = "INVALID_SESSION_TOKEN"
    override def isInvalidSessionToken: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object SESSION_TOKEN_EXPIRED extends ResultCode {
    val value = 50002
    val index = 12
    val name = "SESSION_TOKEN_EXPIRED"
    override def isSessionTokenExpired: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object ILLEGAL_ARGUMENT extends ResultCode {
    val value = 60001
    val index = 13
    val name = "ILLEGAL_ARGUMENT"
    override def isIllegalArgument: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case class Unrecognized(value: Int) extends ResultCode {
    val name = "UNRECOGNIZED"
    val index = -1
    override def isUnrecognized: Boolean = true
  }
  
  lazy val values = Seq(RESULT_CODE_EMPTY, SUCCESS, INTERNAL_SERVER_ERROR, INVALID_REQUEST_ARGUMENT, ORDER_NOT_EXISTED, INVALID_ORDER_STATE, INVALID_PHONENUM, INVALID_EMAIL, PHONENUM_ALREADY_EXISTED, EMAIL_ALREADY_EXISTED, INVALID_PASSWORD, INVALID_SESSION_TOKEN, SESSION_TOKEN_EXPIRED, ILLEGAL_ARGUMENT)
  def fromValue(value: Int): ResultCode = value match {
    case 0 => RESULT_CODE_EMPTY
    case 1 => SUCCESS
    case 10000 => INTERNAL_SERVER_ERROR
    case 20001 => INVALID_REQUEST_ARGUMENT
    case 30001 => ORDER_NOT_EXISTED
    case 30002 => INVALID_ORDER_STATE
    case 40001 => INVALID_PHONENUM
    case 40002 => INVALID_EMAIL
    case 40005 => PHONENUM_ALREADY_EXISTED
    case 40006 => EMAIL_ALREADY_EXISTED
    case 40011 => INVALID_PASSWORD
    case 50001 => INVALID_SESSION_TOKEN
    case 50002 => SESSION_TOKEN_EXPIRED
    case 60001 => ILLEGAL_ARGUMENT
    case __other => Unrecognized(__other)
  }
  def descriptor: com.google.protobuf.Descriptors.EnumDescriptor = CommonProto.descriptor.getEnumTypes.get(0)
}